// Code generated by ent, DO NOT EDIT.

package ticket

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the ticket type in the database.
	Label = "ticket"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldQuestion holds the string denoting the question field in the database.
	FieldQuestion = "question"
	// FieldState holds the string denoting the state field in the database.
	FieldState = "state"
	// FieldPriority holds the string denoting the priority field in the database.
	FieldPriority = "priority"
	// FieldStateJob holds the string denoting the state_job field in the database.
	FieldStateJob = "state_job"
	// FieldDataAssigned holds the string denoting the data_assigned field in the database.
	FieldDataAssigned = "data_assigned"
	// FieldDataCreation holds the string denoting the data_creation field in the database.
	FieldDataCreation = "data_creation"
	// FieldDataUpdating holds the string denoting the data_updating field in the database.
	FieldDataUpdating = "data_updating"
	// EdgeCompany holds the string denoting the company edge name in mutations.
	EdgeCompany = "company"
	// EdgeServiceCenter holds the string denoting the service_center edge name in mutations.
	EdgeServiceCenter = "service_center"
	// EdgeAssignedTo holds the string denoting the assigned_to edge name in mutations.
	EdgeAssignedTo = "assigned_to"
	// EdgeCreatedBy holds the string denoting the created_by edge name in mutations.
	EdgeCreatedBy = "created_by"
	// EdgeUpdatedBy holds the string denoting the updated_by edge name in mutations.
	EdgeUpdatedBy = "updated_by"
	// EdgeComments holds the string denoting the comments edge name in mutations.
	EdgeComments = "comments"
	// EdgeAttachments holds the string denoting the attachments edge name in mutations.
	EdgeAttachments = "attachments"
	// Table holds the table name of the ticket in the database.
	Table = "tickets"
	// CompanyTable is the table that holds the company relation/edge.
	CompanyTable = "tickets"
	// CompanyInverseTable is the table name for the Company entity.
	// It exists in this package in order to avoid circular dependency with the "company" package.
	CompanyInverseTable = "companies"
	// CompanyColumn is the table column denoting the company relation/edge.
	CompanyColumn = "company_tickets"
	// ServiceCenterTable is the table that holds the service_center relation/edge.
	ServiceCenterTable = "tickets"
	// ServiceCenterInverseTable is the table name for the ServiceCenter entity.
	// It exists in this package in order to avoid circular dependency with the "servicecenter" package.
	ServiceCenterInverseTable = "service_centers"
	// ServiceCenterColumn is the table column denoting the service_center relation/edge.
	ServiceCenterColumn = "service_center_tickets"
	// AssignedToTable is the table that holds the assigned_to relation/edge.
	AssignedToTable = "tickets"
	// AssignedToInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	AssignedToInverseTable = "users"
	// AssignedToColumn is the table column denoting the assigned_to relation/edge.
	AssignedToColumn = "assigned_to_id"
	// CreatedByTable is the table that holds the created_by relation/edge.
	CreatedByTable = "tickets"
	// CreatedByInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	CreatedByInverseTable = "users"
	// CreatedByColumn is the table column denoting the created_by relation/edge.
	CreatedByColumn = "created_by_id"
	// UpdatedByTable is the table that holds the updated_by relation/edge.
	UpdatedByTable = "tickets"
	// UpdatedByInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UpdatedByInverseTable = "users"
	// UpdatedByColumn is the table column denoting the updated_by relation/edge.
	UpdatedByColumn = "updated_by_id"
	// CommentsTable is the table that holds the comments relation/edge.
	CommentsTable = "comments"
	// CommentsInverseTable is the table name for the Comment entity.
	// It exists in this package in order to avoid circular dependency with the "comment" package.
	CommentsInverseTable = "comments"
	// CommentsColumn is the table column denoting the comments relation/edge.
	CommentsColumn = "ticket_comments"
	// AttachmentsTable is the table that holds the attachments relation/edge.
	AttachmentsTable = "attachments"
	// AttachmentsInverseTable is the table name for the Attachment entity.
	// It exists in this package in order to avoid circular dependency with the "attachment" package.
	AttachmentsInverseTable = "attachments"
	// AttachmentsColumn is the table column denoting the attachments relation/edge.
	AttachmentsColumn = "ticket_attachments"
)

// Columns holds all SQL columns for ticket fields.
var Columns = []string{
	FieldID,
	FieldTitle,
	FieldQuestion,
	FieldState,
	FieldPriority,
	FieldStateJob,
	FieldDataAssigned,
	FieldDataCreation,
	FieldDataUpdating,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "tickets"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"company_tickets",
	"service_center_tickets",
	"assigned_to_id",
	"created_by_id",
	"updated_by_id",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// TitleValidator is a validator for the "title" field. It is called by the builders before save.
	TitleValidator func(string) error
	// DefaultDataCreation holds the default value on creation for the "data_creation" field.
	DefaultDataCreation func() time.Time
	// DefaultDataUpdating holds the default value on creation for the "data_updating" field.
	DefaultDataUpdating func() time.Time
	// UpdateDefaultDataUpdating holds the default value on update for the "data_updating" field.
	UpdateDefaultDataUpdating func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// State defines the type for the "state" enum field.
type State string

// StateOPEN is the default value of the State enum.
const DefaultState = StateOPEN

// State values.
const (
	StateOPEN   State = "OPEN"
	StateCLOSED State = "CLOSED"
	StateTODO   State = "TODO"
	StateWAIT   State = "WAIT"
)

func (s State) String() string {
	return string(s)
}

// StateValidator is a validator for the "state" field enum values. It is called by the builders before save.
func StateValidator(s State) error {
	switch s {
	case StateOPEN, StateCLOSED, StateTODO, StateWAIT:
		return nil
	default:
		return fmt.Errorf("ticket: invalid enum value for state field: %q", s)
	}
}

// Priority defines the type for the "priority" enum field.
type Priority string

// PriorityLOW is the default value of the Priority enum.
const DefaultPriority = PriorityLOW

// Priority values.
const (
	PriorityLOW    Priority = "LOW"
	PriorityMEDIUM Priority = "MEDIUM"
	PriorityHIGH   Priority = "HIGH"
)

func (pr Priority) String() string {
	return string(pr)
}

// PriorityValidator is a validator for the "priority" field enum values. It is called by the builders before save.
func PriorityValidator(pr Priority) error {
	switch pr {
	case PriorityLOW, PriorityMEDIUM, PriorityHIGH:
		return nil
	default:
		return fmt.Errorf("ticket: invalid enum value for priority field: %q", pr)
	}
}

// StateJob defines the type for the "state_job" enum field.
type StateJob string

// StateJobAPERTA is the default value of the StateJob enum.
const DefaultStateJob = StateJobAPERTA

// StateJob values.
const (
	StateJobAPERTA                   StateJob = "APERTA"
	StateJobIN_ATTESA_CLIENTE        StateJob = "IN_ATTESA_CLIENTE"
	StateJobPRESA_IN_CARICO          StateJob = "PRESA_IN_CARICO"
	StateJobIN_ATTESA_CENTRO_SERVIZI StateJob = "IN_ATTESA_CENTRO_SERVIZI"
	StateJobCHIUSA                   StateJob = "CHIUSA"
)

func (sj StateJob) String() string {
	return string(sj)
}

// StateJobValidator is a validator for the "state_job" field enum values. It is called by the builders before save.
func StateJobValidator(sj StateJob) error {
	switch sj {
	case StateJobAPERTA, StateJobIN_ATTESA_CLIENTE, StateJobPRESA_IN_CARICO, StateJobIN_ATTESA_CENTRO_SERVIZI, StateJobCHIUSA:
		return nil
	default:
		return fmt.Errorf("ticket: invalid enum value for state_job field: %q", sj)
	}
}

// OrderOption defines the ordering options for the Ticket queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTitle orders the results by the title field.
func ByTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitle, opts...).ToFunc()
}

// ByQuestion orders the results by the question field.
func ByQuestion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQuestion, opts...).ToFunc()
}

// ByState orders the results by the state field.
func ByState(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldState, opts...).ToFunc()
}

// ByPriority orders the results by the priority field.
func ByPriority(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPriority, opts...).ToFunc()
}

// ByStateJob orders the results by the state_job field.
func ByStateJob(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStateJob, opts...).ToFunc()
}

// ByDataAssigned orders the results by the data_assigned field.
func ByDataAssigned(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDataAssigned, opts...).ToFunc()
}

// ByDataCreation orders the results by the data_creation field.
func ByDataCreation(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDataCreation, opts...).ToFunc()
}

// ByDataUpdating orders the results by the data_updating field.
func ByDataUpdating(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDataUpdating, opts...).ToFunc()
}

// ByCompanyField orders the results by company field.
func ByCompanyField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCompanyStep(), sql.OrderByField(field, opts...))
	}
}

// ByServiceCenterField orders the results by service_center field.
func ByServiceCenterField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newServiceCenterStep(), sql.OrderByField(field, opts...))
	}
}

// ByAssignedToField orders the results by assigned_to field.
func ByAssignedToField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAssignedToStep(), sql.OrderByField(field, opts...))
	}
}

// ByCreatedByField orders the results by created_by field.
func ByCreatedByField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCreatedByStep(), sql.OrderByField(field, opts...))
	}
}

// ByUpdatedByField orders the results by updated_by field.
func ByUpdatedByField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUpdatedByStep(), sql.OrderByField(field, opts...))
	}
}

// ByCommentsCount orders the results by comments count.
func ByCommentsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newCommentsStep(), opts...)
	}
}

// ByComments orders the results by comments terms.
func ByComments(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCommentsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByAttachmentsCount orders the results by attachments count.
func ByAttachmentsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newAttachmentsStep(), opts...)
	}
}

// ByAttachments orders the results by attachments terms.
func ByAttachments(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAttachmentsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newCompanyStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CompanyInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, CompanyTable, CompanyColumn),
	)
}
func newServiceCenterStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ServiceCenterInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ServiceCenterTable, ServiceCenterColumn),
	)
}
func newAssignedToStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AssignedToInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, AssignedToTable, AssignedToColumn),
	)
}
func newCreatedByStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CreatedByInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, CreatedByTable, CreatedByColumn),
	)
}
func newUpdatedByStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UpdatedByInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UpdatedByTable, UpdatedByColumn),
	)
}
func newCommentsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CommentsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, CommentsTable, CommentsColumn),
	)
}
func newAttachmentsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AttachmentsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, AttachmentsTable, AttachmentsColumn),
	)
}
