// Code generated by ent, DO NOT EDIT.

package ticket

import (
	"ticket-service/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Ticket {
	return predicate.Ticket(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Ticket {
	return predicate.Ticket(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Ticket {
	return predicate.Ticket(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Ticket {
	return predicate.Ticket(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Ticket {
	return predicate.Ticket(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Ticket {
	return predicate.Ticket(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Ticket {
	return predicate.Ticket(sql.FieldLTE(FieldID, id))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldTitle, v))
}

// Question applies equality check predicate on the "question" field. It's identical to QuestionEQ.
func Question(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldQuestion, v))
}

// DataAssigned applies equality check predicate on the "data_assigned" field. It's identical to DataAssignedEQ.
func DataAssigned(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldDataAssigned, v))
}

// DataCreation applies equality check predicate on the "data_creation" field. It's identical to DataCreationEQ.
func DataCreation(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldDataCreation, v))
}

// DataUpdating applies equality check predicate on the "data_updating" field. It's identical to DataUpdatingEQ.
func DataUpdating(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldDataUpdating, v))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.Ticket {
	return predicate.Ticket(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.Ticket {
	return predicate.Ticket(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldContainsFold(FieldTitle, v))
}

// QuestionEQ applies the EQ predicate on the "question" field.
func QuestionEQ(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldQuestion, v))
}

// QuestionNEQ applies the NEQ predicate on the "question" field.
func QuestionNEQ(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldNEQ(FieldQuestion, v))
}

// QuestionIn applies the In predicate on the "question" field.
func QuestionIn(vs ...string) predicate.Ticket {
	return predicate.Ticket(sql.FieldIn(FieldQuestion, vs...))
}

// QuestionNotIn applies the NotIn predicate on the "question" field.
func QuestionNotIn(vs ...string) predicate.Ticket {
	return predicate.Ticket(sql.FieldNotIn(FieldQuestion, vs...))
}

// QuestionGT applies the GT predicate on the "question" field.
func QuestionGT(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldGT(FieldQuestion, v))
}

// QuestionGTE applies the GTE predicate on the "question" field.
func QuestionGTE(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldGTE(FieldQuestion, v))
}

// QuestionLT applies the LT predicate on the "question" field.
func QuestionLT(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldLT(FieldQuestion, v))
}

// QuestionLTE applies the LTE predicate on the "question" field.
func QuestionLTE(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldLTE(FieldQuestion, v))
}

// QuestionContains applies the Contains predicate on the "question" field.
func QuestionContains(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldContains(FieldQuestion, v))
}

// QuestionHasPrefix applies the HasPrefix predicate on the "question" field.
func QuestionHasPrefix(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldHasPrefix(FieldQuestion, v))
}

// QuestionHasSuffix applies the HasSuffix predicate on the "question" field.
func QuestionHasSuffix(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldHasSuffix(FieldQuestion, v))
}

// QuestionEqualFold applies the EqualFold predicate on the "question" field.
func QuestionEqualFold(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldEqualFold(FieldQuestion, v))
}

// QuestionContainsFold applies the ContainsFold predicate on the "question" field.
func QuestionContainsFold(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldContainsFold(FieldQuestion, v))
}

// StateEQ applies the EQ predicate on the "state" field.
func StateEQ(v State) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldState, v))
}

// StateNEQ applies the NEQ predicate on the "state" field.
func StateNEQ(v State) predicate.Ticket {
	return predicate.Ticket(sql.FieldNEQ(FieldState, v))
}

// StateIn applies the In predicate on the "state" field.
func StateIn(vs ...State) predicate.Ticket {
	return predicate.Ticket(sql.FieldIn(FieldState, vs...))
}

// StateNotIn applies the NotIn predicate on the "state" field.
func StateNotIn(vs ...State) predicate.Ticket {
	return predicate.Ticket(sql.FieldNotIn(FieldState, vs...))
}

// PriorityEQ applies the EQ predicate on the "priority" field.
func PriorityEQ(v Priority) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldPriority, v))
}

// PriorityNEQ applies the NEQ predicate on the "priority" field.
func PriorityNEQ(v Priority) predicate.Ticket {
	return predicate.Ticket(sql.FieldNEQ(FieldPriority, v))
}

// PriorityIn applies the In predicate on the "priority" field.
func PriorityIn(vs ...Priority) predicate.Ticket {
	return predicate.Ticket(sql.FieldIn(FieldPriority, vs...))
}

// PriorityNotIn applies the NotIn predicate on the "priority" field.
func PriorityNotIn(vs ...Priority) predicate.Ticket {
	return predicate.Ticket(sql.FieldNotIn(FieldPriority, vs...))
}

// StateJobEQ applies the EQ predicate on the "state_job" field.
func StateJobEQ(v StateJob) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldStateJob, v))
}

// StateJobNEQ applies the NEQ predicate on the "state_job" field.
func StateJobNEQ(v StateJob) predicate.Ticket {
	return predicate.Ticket(sql.FieldNEQ(FieldStateJob, v))
}

// StateJobIn applies the In predicate on the "state_job" field.
func StateJobIn(vs ...StateJob) predicate.Ticket {
	return predicate.Ticket(sql.FieldIn(FieldStateJob, vs...))
}

// StateJobNotIn applies the NotIn predicate on the "state_job" field.
func StateJobNotIn(vs ...StateJob) predicate.Ticket {
	return predicate.Ticket(sql.FieldNotIn(FieldStateJob, vs...))
}

// DataAssignedEQ applies the EQ predicate on the "data_assigned" field.
func DataAssignedEQ(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldDataAssigned, v))
}

// DataAssignedNEQ applies the NEQ predicate on the "data_assigned" field.
func DataAssignedNEQ(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldNEQ(FieldDataAssigned, v))
}

// DataAssignedIn applies the In predicate on the "data_assigned" field.
func DataAssignedIn(vs ...time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldIn(FieldDataAssigned, vs...))
}

// DataAssignedNotIn applies the NotIn predicate on the "data_assigned" field.
func DataAssignedNotIn(vs ...time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldNotIn(FieldDataAssigned, vs...))
}

// DataAssignedGT applies the GT predicate on the "data_assigned" field.
func DataAssignedGT(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldGT(FieldDataAssigned, v))
}

// DataAssignedGTE applies the GTE predicate on the "data_assigned" field.
func DataAssignedGTE(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldGTE(FieldDataAssigned, v))
}

// DataAssignedLT applies the LT predicate on the "data_assigned" field.
func DataAssignedLT(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldLT(FieldDataAssigned, v))
}

// DataAssignedLTE applies the LTE predicate on the "data_assigned" field.
func DataAssignedLTE(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldLTE(FieldDataAssigned, v))
}

// DataAssignedIsNil applies the IsNil predicate on the "data_assigned" field.
func DataAssignedIsNil() predicate.Ticket {
	return predicate.Ticket(sql.FieldIsNull(FieldDataAssigned))
}

// DataAssignedNotNil applies the NotNil predicate on the "data_assigned" field.
func DataAssignedNotNil() predicate.Ticket {
	return predicate.Ticket(sql.FieldNotNull(FieldDataAssigned))
}

// DataCreationEQ applies the EQ predicate on the "data_creation" field.
func DataCreationEQ(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldDataCreation, v))
}

// DataCreationNEQ applies the NEQ predicate on the "data_creation" field.
func DataCreationNEQ(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldNEQ(FieldDataCreation, v))
}

// DataCreationIn applies the In predicate on the "data_creation" field.
func DataCreationIn(vs ...time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldIn(FieldDataCreation, vs...))
}

// DataCreationNotIn applies the NotIn predicate on the "data_creation" field.
func DataCreationNotIn(vs ...time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldNotIn(FieldDataCreation, vs...))
}

// DataCreationGT applies the GT predicate on the "data_creation" field.
func DataCreationGT(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldGT(FieldDataCreation, v))
}

// DataCreationGTE applies the GTE predicate on the "data_creation" field.
func DataCreationGTE(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldGTE(FieldDataCreation, v))
}

// DataCreationLT applies the LT predicate on the "data_creation" field.
func DataCreationLT(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldLT(FieldDataCreation, v))
}

// DataCreationLTE applies the LTE predicate on the "data_creation" field.
func DataCreationLTE(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldLTE(FieldDataCreation, v))
}

// DataUpdatingEQ applies the EQ predicate on the "data_updating" field.
func DataUpdatingEQ(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldDataUpdating, v))
}

// DataUpdatingNEQ applies the NEQ predicate on the "data_updating" field.
func DataUpdatingNEQ(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldNEQ(FieldDataUpdating, v))
}

// DataUpdatingIn applies the In predicate on the "data_updating" field.
func DataUpdatingIn(vs ...time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldIn(FieldDataUpdating, vs...))
}

// DataUpdatingNotIn applies the NotIn predicate on the "data_updating" field.
func DataUpdatingNotIn(vs ...time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldNotIn(FieldDataUpdating, vs...))
}

// DataUpdatingGT applies the GT predicate on the "data_updating" field.
func DataUpdatingGT(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldGT(FieldDataUpdating, v))
}

// DataUpdatingGTE applies the GTE predicate on the "data_updating" field.
func DataUpdatingGTE(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldGTE(FieldDataUpdating, v))
}

// DataUpdatingLT applies the LT predicate on the "data_updating" field.
func DataUpdatingLT(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldLT(FieldDataUpdating, v))
}

// DataUpdatingLTE applies the LTE predicate on the "data_updating" field.
func DataUpdatingLTE(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldLTE(FieldDataUpdating, v))
}

// HasCompany applies the HasEdge predicate on the "company" edge.
func HasCompany() predicate.Ticket {
	return predicate.Ticket(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, CompanyTable, CompanyColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCompanyWith applies the HasEdge predicate on the "company" edge with a given conditions (other predicates).
func HasCompanyWith(preds ...predicate.Company) predicate.Ticket {
	return predicate.Ticket(func(s *sql.Selector) {
		step := newCompanyStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasServiceCenter applies the HasEdge predicate on the "service_center" edge.
func HasServiceCenter() predicate.Ticket {
	return predicate.Ticket(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ServiceCenterTable, ServiceCenterColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasServiceCenterWith applies the HasEdge predicate on the "service_center" edge with a given conditions (other predicates).
func HasServiceCenterWith(preds ...predicate.ServiceCenter) predicate.Ticket {
	return predicate.Ticket(func(s *sql.Selector) {
		step := newServiceCenterStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAssignedTo applies the HasEdge predicate on the "assigned_to" edge.
func HasAssignedTo() predicate.Ticket {
	return predicate.Ticket(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, AssignedToTable, AssignedToColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAssignedToWith applies the HasEdge predicate on the "assigned_to" edge with a given conditions (other predicates).
func HasAssignedToWith(preds ...predicate.User) predicate.Ticket {
	return predicate.Ticket(func(s *sql.Selector) {
		step := newAssignedToStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasCreatedBy applies the HasEdge predicate on the "created_by" edge.
func HasCreatedBy() predicate.Ticket {
	return predicate.Ticket(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, CreatedByTable, CreatedByColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCreatedByWith applies the HasEdge predicate on the "created_by" edge with a given conditions (other predicates).
func HasCreatedByWith(preds ...predicate.User) predicate.Ticket {
	return predicate.Ticket(func(s *sql.Selector) {
		step := newCreatedByStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUpdatedBy applies the HasEdge predicate on the "updated_by" edge.
func HasUpdatedBy() predicate.Ticket {
	return predicate.Ticket(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UpdatedByTable, UpdatedByColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUpdatedByWith applies the HasEdge predicate on the "updated_by" edge with a given conditions (other predicates).
func HasUpdatedByWith(preds ...predicate.User) predicate.Ticket {
	return predicate.Ticket(func(s *sql.Selector) {
		step := newUpdatedByStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasComments applies the HasEdge predicate on the "comments" edge.
func HasComments() predicate.Ticket {
	return predicate.Ticket(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, CommentsTable, CommentsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCommentsWith applies the HasEdge predicate on the "comments" edge with a given conditions (other predicates).
func HasCommentsWith(preds ...predicate.Comment) predicate.Ticket {
	return predicate.Ticket(func(s *sql.Selector) {
		step := newCommentsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAttachments applies the HasEdge predicate on the "attachments" edge.
func HasAttachments() predicate.Ticket {
	return predicate.Ticket(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, AttachmentsTable, AttachmentsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAttachmentsWith applies the HasEdge predicate on the "attachments" edge with a given conditions (other predicates).
func HasAttachmentsWith(preds ...predicate.Attachment) predicate.Ticket {
	return predicate.Ticket(func(s *sql.Selector) {
		step := newAttachmentsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Ticket) predicate.Ticket {
	return predicate.Ticket(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Ticket) predicate.Ticket {
	return predicate.Ticket(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Ticket) predicate.Ticket {
	return predicate.Ticket(sql.NotPredicates(p))
}
