// Code generated by ent, DO NOT EDIT.

package company

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the company type in the database.
	Label = "company"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCodice holds the string denoting the codice field in the database.
	FieldCodice = "codice"
	// FieldRagioneSociale holds the string denoting the ragione_sociale field in the database.
	FieldRagioneSociale = "ragione_sociale"
	// FieldPiva holds the string denoting the piva field in the database.
	FieldPiva = "piva"
	// FieldCf holds the string denoting the cf field in the database.
	FieldCf = "cf"
	// FieldActive holds the string denoting the active field in the database.
	FieldActive = "active"
	// EdgeUsers holds the string denoting the users edge name in mutations.
	EdgeUsers = "users"
	// EdgeTickets holds the string denoting the tickets edge name in mutations.
	EdgeTickets = "tickets"
	// Table holds the table name of the company in the database.
	Table = "companies"
	// UsersTable is the table that holds the users relation/edge.
	UsersTable = "users"
	// UsersInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UsersInverseTable = "users"
	// UsersColumn is the table column denoting the users relation/edge.
	UsersColumn = "company_users"
	// TicketsTable is the table that holds the tickets relation/edge.
	TicketsTable = "tickets"
	// TicketsInverseTable is the table name for the Ticket entity.
	// It exists in this package in order to avoid circular dependency with the "ticket" package.
	TicketsInverseTable = "tickets"
	// TicketsColumn is the table column denoting the tickets relation/edge.
	TicketsColumn = "company_tickets"
)

// Columns holds all SQL columns for company fields.
var Columns = []string{
	FieldID,
	FieldCodice,
	FieldRagioneSociale,
	FieldPiva,
	FieldCf,
	FieldActive,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// CodiceValidator is a validator for the "codice" field. It is called by the builders before save.
	CodiceValidator func(string) error
	// RagioneSocialeValidator is a validator for the "ragione_sociale" field. It is called by the builders before save.
	RagioneSocialeValidator func(string) error
	// PivaValidator is a validator for the "piva" field. It is called by the builders before save.
	PivaValidator func(string) error
	// CfValidator is a validator for the "cf" field. It is called by the builders before save.
	CfValidator func(string) error
	// DefaultActive holds the default value on creation for the "active" field.
	DefaultActive bool
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the Company queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCodice orders the results by the codice field.
func ByCodice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCodice, opts...).ToFunc()
}

// ByRagioneSociale orders the results by the ragione_sociale field.
func ByRagioneSociale(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRagioneSociale, opts...).ToFunc()
}

// ByPiva orders the results by the piva field.
func ByPiva(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPiva, opts...).ToFunc()
}

// ByCf orders the results by the cf field.
func ByCf(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCf, opts...).ToFunc()
}

// ByActive orders the results by the active field.
func ByActive(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActive, opts...).ToFunc()
}

// ByUsersCount orders the results by users count.
func ByUsersCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newUsersStep(), opts...)
	}
}

// ByUsers orders the results by users terms.
func ByUsers(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUsersStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByTicketsCount orders the results by tickets count.
func ByTicketsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newTicketsStep(), opts...)
	}
}

// ByTickets orders the results by tickets terms.
func ByTickets(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTicketsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newUsersStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UsersInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, UsersTable, UsersColumn),
	)
}
func newTicketsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TicketsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, TicketsTable, TicketsColumn),
	)
}
