// Code generated by ent, DO NOT EDIT.

package company

import (
	"ticket-service/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Company {
	return predicate.Company(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Company {
	return predicate.Company(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Company {
	return predicate.Company(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Company {
	return predicate.Company(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Company {
	return predicate.Company(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Company {
	return predicate.Company(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Company {
	return predicate.Company(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Company {
	return predicate.Company(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Company {
	return predicate.Company(sql.FieldLTE(FieldID, id))
}

// Codice applies equality check predicate on the "codice" field. It's identical to CodiceEQ.
func Codice(v string) predicate.Company {
	return predicate.Company(sql.FieldEQ(FieldCodice, v))
}

// RagioneSociale applies equality check predicate on the "ragione_sociale" field. It's identical to RagioneSocialeEQ.
func RagioneSociale(v string) predicate.Company {
	return predicate.Company(sql.FieldEQ(FieldRagioneSociale, v))
}

// Piva applies equality check predicate on the "piva" field. It's identical to PivaEQ.
func Piva(v string) predicate.Company {
	return predicate.Company(sql.FieldEQ(FieldPiva, v))
}

// Cf applies equality check predicate on the "cf" field. It's identical to CfEQ.
func Cf(v string) predicate.Company {
	return predicate.Company(sql.FieldEQ(FieldCf, v))
}

// Active applies equality check predicate on the "active" field. It's identical to ActiveEQ.
func Active(v bool) predicate.Company {
	return predicate.Company(sql.FieldEQ(FieldActive, v))
}

// CodiceEQ applies the EQ predicate on the "codice" field.
func CodiceEQ(v string) predicate.Company {
	return predicate.Company(sql.FieldEQ(FieldCodice, v))
}

// CodiceNEQ applies the NEQ predicate on the "codice" field.
func CodiceNEQ(v string) predicate.Company {
	return predicate.Company(sql.FieldNEQ(FieldCodice, v))
}

// CodiceIn applies the In predicate on the "codice" field.
func CodiceIn(vs ...string) predicate.Company {
	return predicate.Company(sql.FieldIn(FieldCodice, vs...))
}

// CodiceNotIn applies the NotIn predicate on the "codice" field.
func CodiceNotIn(vs ...string) predicate.Company {
	return predicate.Company(sql.FieldNotIn(FieldCodice, vs...))
}

// CodiceGT applies the GT predicate on the "codice" field.
func CodiceGT(v string) predicate.Company {
	return predicate.Company(sql.FieldGT(FieldCodice, v))
}

// CodiceGTE applies the GTE predicate on the "codice" field.
func CodiceGTE(v string) predicate.Company {
	return predicate.Company(sql.FieldGTE(FieldCodice, v))
}

// CodiceLT applies the LT predicate on the "codice" field.
func CodiceLT(v string) predicate.Company {
	return predicate.Company(sql.FieldLT(FieldCodice, v))
}

// CodiceLTE applies the LTE predicate on the "codice" field.
func CodiceLTE(v string) predicate.Company {
	return predicate.Company(sql.FieldLTE(FieldCodice, v))
}

// CodiceContains applies the Contains predicate on the "codice" field.
func CodiceContains(v string) predicate.Company {
	return predicate.Company(sql.FieldContains(FieldCodice, v))
}

// CodiceHasPrefix applies the HasPrefix predicate on the "codice" field.
func CodiceHasPrefix(v string) predicate.Company {
	return predicate.Company(sql.FieldHasPrefix(FieldCodice, v))
}

// CodiceHasSuffix applies the HasSuffix predicate on the "codice" field.
func CodiceHasSuffix(v string) predicate.Company {
	return predicate.Company(sql.FieldHasSuffix(FieldCodice, v))
}

// CodiceEqualFold applies the EqualFold predicate on the "codice" field.
func CodiceEqualFold(v string) predicate.Company {
	return predicate.Company(sql.FieldEqualFold(FieldCodice, v))
}

// CodiceContainsFold applies the ContainsFold predicate on the "codice" field.
func CodiceContainsFold(v string) predicate.Company {
	return predicate.Company(sql.FieldContainsFold(FieldCodice, v))
}

// RagioneSocialeEQ applies the EQ predicate on the "ragione_sociale" field.
func RagioneSocialeEQ(v string) predicate.Company {
	return predicate.Company(sql.FieldEQ(FieldRagioneSociale, v))
}

// RagioneSocialeNEQ applies the NEQ predicate on the "ragione_sociale" field.
func RagioneSocialeNEQ(v string) predicate.Company {
	return predicate.Company(sql.FieldNEQ(FieldRagioneSociale, v))
}

// RagioneSocialeIn applies the In predicate on the "ragione_sociale" field.
func RagioneSocialeIn(vs ...string) predicate.Company {
	return predicate.Company(sql.FieldIn(FieldRagioneSociale, vs...))
}

// RagioneSocialeNotIn applies the NotIn predicate on the "ragione_sociale" field.
func RagioneSocialeNotIn(vs ...string) predicate.Company {
	return predicate.Company(sql.FieldNotIn(FieldRagioneSociale, vs...))
}

// RagioneSocialeGT applies the GT predicate on the "ragione_sociale" field.
func RagioneSocialeGT(v string) predicate.Company {
	return predicate.Company(sql.FieldGT(FieldRagioneSociale, v))
}

// RagioneSocialeGTE applies the GTE predicate on the "ragione_sociale" field.
func RagioneSocialeGTE(v string) predicate.Company {
	return predicate.Company(sql.FieldGTE(FieldRagioneSociale, v))
}

// RagioneSocialeLT applies the LT predicate on the "ragione_sociale" field.
func RagioneSocialeLT(v string) predicate.Company {
	return predicate.Company(sql.FieldLT(FieldRagioneSociale, v))
}

// RagioneSocialeLTE applies the LTE predicate on the "ragione_sociale" field.
func RagioneSocialeLTE(v string) predicate.Company {
	return predicate.Company(sql.FieldLTE(FieldRagioneSociale, v))
}

// RagioneSocialeContains applies the Contains predicate on the "ragione_sociale" field.
func RagioneSocialeContains(v string) predicate.Company {
	return predicate.Company(sql.FieldContains(FieldRagioneSociale, v))
}

// RagioneSocialeHasPrefix applies the HasPrefix predicate on the "ragione_sociale" field.
func RagioneSocialeHasPrefix(v string) predicate.Company {
	return predicate.Company(sql.FieldHasPrefix(FieldRagioneSociale, v))
}

// RagioneSocialeHasSuffix applies the HasSuffix predicate on the "ragione_sociale" field.
func RagioneSocialeHasSuffix(v string) predicate.Company {
	return predicate.Company(sql.FieldHasSuffix(FieldRagioneSociale, v))
}

// RagioneSocialeEqualFold applies the EqualFold predicate on the "ragione_sociale" field.
func RagioneSocialeEqualFold(v string) predicate.Company {
	return predicate.Company(sql.FieldEqualFold(FieldRagioneSociale, v))
}

// RagioneSocialeContainsFold applies the ContainsFold predicate on the "ragione_sociale" field.
func RagioneSocialeContainsFold(v string) predicate.Company {
	return predicate.Company(sql.FieldContainsFold(FieldRagioneSociale, v))
}

// PivaEQ applies the EQ predicate on the "piva" field.
func PivaEQ(v string) predicate.Company {
	return predicate.Company(sql.FieldEQ(FieldPiva, v))
}

// PivaNEQ applies the NEQ predicate on the "piva" field.
func PivaNEQ(v string) predicate.Company {
	return predicate.Company(sql.FieldNEQ(FieldPiva, v))
}

// PivaIn applies the In predicate on the "piva" field.
func PivaIn(vs ...string) predicate.Company {
	return predicate.Company(sql.FieldIn(FieldPiva, vs...))
}

// PivaNotIn applies the NotIn predicate on the "piva" field.
func PivaNotIn(vs ...string) predicate.Company {
	return predicate.Company(sql.FieldNotIn(FieldPiva, vs...))
}

// PivaGT applies the GT predicate on the "piva" field.
func PivaGT(v string) predicate.Company {
	return predicate.Company(sql.FieldGT(FieldPiva, v))
}

// PivaGTE applies the GTE predicate on the "piva" field.
func PivaGTE(v string) predicate.Company {
	return predicate.Company(sql.FieldGTE(FieldPiva, v))
}

// PivaLT applies the LT predicate on the "piva" field.
func PivaLT(v string) predicate.Company {
	return predicate.Company(sql.FieldLT(FieldPiva, v))
}

// PivaLTE applies the LTE predicate on the "piva" field.
func PivaLTE(v string) predicate.Company {
	return predicate.Company(sql.FieldLTE(FieldPiva, v))
}

// PivaContains applies the Contains predicate on the "piva" field.
func PivaContains(v string) predicate.Company {
	return predicate.Company(sql.FieldContains(FieldPiva, v))
}

// PivaHasPrefix applies the HasPrefix predicate on the "piva" field.
func PivaHasPrefix(v string) predicate.Company {
	return predicate.Company(sql.FieldHasPrefix(FieldPiva, v))
}

// PivaHasSuffix applies the HasSuffix predicate on the "piva" field.
func PivaHasSuffix(v string) predicate.Company {
	return predicate.Company(sql.FieldHasSuffix(FieldPiva, v))
}

// PivaEqualFold applies the EqualFold predicate on the "piva" field.
func PivaEqualFold(v string) predicate.Company {
	return predicate.Company(sql.FieldEqualFold(FieldPiva, v))
}

// PivaContainsFold applies the ContainsFold predicate on the "piva" field.
func PivaContainsFold(v string) predicate.Company {
	return predicate.Company(sql.FieldContainsFold(FieldPiva, v))
}

// CfEQ applies the EQ predicate on the "cf" field.
func CfEQ(v string) predicate.Company {
	return predicate.Company(sql.FieldEQ(FieldCf, v))
}

// CfNEQ applies the NEQ predicate on the "cf" field.
func CfNEQ(v string) predicate.Company {
	return predicate.Company(sql.FieldNEQ(FieldCf, v))
}

// CfIn applies the In predicate on the "cf" field.
func CfIn(vs ...string) predicate.Company {
	return predicate.Company(sql.FieldIn(FieldCf, vs...))
}

// CfNotIn applies the NotIn predicate on the "cf" field.
func CfNotIn(vs ...string) predicate.Company {
	return predicate.Company(sql.FieldNotIn(FieldCf, vs...))
}

// CfGT applies the GT predicate on the "cf" field.
func CfGT(v string) predicate.Company {
	return predicate.Company(sql.FieldGT(FieldCf, v))
}

// CfGTE applies the GTE predicate on the "cf" field.
func CfGTE(v string) predicate.Company {
	return predicate.Company(sql.FieldGTE(FieldCf, v))
}

// CfLT applies the LT predicate on the "cf" field.
func CfLT(v string) predicate.Company {
	return predicate.Company(sql.FieldLT(FieldCf, v))
}

// CfLTE applies the LTE predicate on the "cf" field.
func CfLTE(v string) predicate.Company {
	return predicate.Company(sql.FieldLTE(FieldCf, v))
}

// CfContains applies the Contains predicate on the "cf" field.
func CfContains(v string) predicate.Company {
	return predicate.Company(sql.FieldContains(FieldCf, v))
}

// CfHasPrefix applies the HasPrefix predicate on the "cf" field.
func CfHasPrefix(v string) predicate.Company {
	return predicate.Company(sql.FieldHasPrefix(FieldCf, v))
}

// CfHasSuffix applies the HasSuffix predicate on the "cf" field.
func CfHasSuffix(v string) predicate.Company {
	return predicate.Company(sql.FieldHasSuffix(FieldCf, v))
}

// CfEqualFold applies the EqualFold predicate on the "cf" field.
func CfEqualFold(v string) predicate.Company {
	return predicate.Company(sql.FieldEqualFold(FieldCf, v))
}

// CfContainsFold applies the ContainsFold predicate on the "cf" field.
func CfContainsFold(v string) predicate.Company {
	return predicate.Company(sql.FieldContainsFold(FieldCf, v))
}

// ActiveEQ applies the EQ predicate on the "active" field.
func ActiveEQ(v bool) predicate.Company {
	return predicate.Company(sql.FieldEQ(FieldActive, v))
}

// ActiveNEQ applies the NEQ predicate on the "active" field.
func ActiveNEQ(v bool) predicate.Company {
	return predicate.Company(sql.FieldNEQ(FieldActive, v))
}

// HasUsers applies the HasEdge predicate on the "users" edge.
func HasUsers() predicate.Company {
	return predicate.Company(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, UsersTable, UsersColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUsersWith applies the HasEdge predicate on the "users" edge with a given conditions (other predicates).
func HasUsersWith(preds ...predicate.User) predicate.Company {
	return predicate.Company(func(s *sql.Selector) {
		step := newUsersStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTickets applies the HasEdge predicate on the "tickets" edge.
func HasTickets() predicate.Company {
	return predicate.Company(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, TicketsTable, TicketsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTicketsWith applies the HasEdge predicate on the "tickets" edge with a given conditions (other predicates).
func HasTicketsWith(preds ...predicate.Ticket) predicate.Company {
	return predicate.Company(func(s *sql.Selector) {
		step := newTicketsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Company) predicate.Company {
	return predicate.Company(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Company) predicate.Company {
	return predicate.Company(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Company) predicate.Company {
	return predicate.Company(sql.NotPredicates(p))
}
