// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AttachmentsColumns holds the columns for the "attachments" table.
	AttachmentsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString, Size: 500},
		{Name: "path", Type: field.TypeString, Size: 2000},
		{Name: "mime_type", Type: field.TypeString, Nullable: true, Size: 100},
		{Name: "size_bytes", Type: field.TypeInt64, Nullable: true},
		{Name: "uploaded_at", Type: field.TypeTime},
		{Name: "comment_attachments", Type: field.TypeUUID, Nullable: true},
		{Name: "ticket_attachments", Type: field.TypeUUID, Nullable: true},
		{Name: "user_attachments", Type: field.TypeUUID, Nullable: true},
	}
	// AttachmentsTable holds the schema information for the "attachments" table.
	AttachmentsTable = &schema.Table{
		Name:       "attachments",
		Columns:    AttachmentsColumns,
		PrimaryKey: []*schema.Column{AttachmentsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "attachments_comments_attachments",
				Columns:    []*schema.Column{AttachmentsColumns[6]},
				RefColumns: []*schema.Column{CommentsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "attachments_tickets_attachments",
				Columns:    []*schema.Column{AttachmentsColumns[7]},
				RefColumns: []*schema.Column{TicketsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "attachments_users_attachments",
				Columns:    []*schema.Column{AttachmentsColumns[8]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// CommentsColumns holds the columns for the "comments" table.
	CommentsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "order_comment", Type: field.TypeInt},
		{Name: "comment_detail", Type: field.TypeString, Size: 2147483647},
		{Name: "data_creation", Type: field.TypeTime},
		{Name: "ticket_comments", Type: field.TypeUUID},
		{Name: "user_comments", Type: field.TypeUUID},
	}
	// CommentsTable holds the schema information for the "comments" table.
	CommentsTable = &schema.Table{
		Name:       "comments",
		Columns:    CommentsColumns,
		PrimaryKey: []*schema.Column{CommentsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "comments_tickets_comments",
				Columns:    []*schema.Column{CommentsColumns[4]},
				RefColumns: []*schema.Column{TicketsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "comments_users_comments",
				Columns:    []*schema.Column{CommentsColumns[5]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// CompaniesColumns holds the columns for the "companies" table.
	CompaniesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "codice", Type: field.TypeString, Unique: true, Size: 15},
		{Name: "ragione_sociale", Type: field.TypeString, Size: 200},
		{Name: "piva", Type: field.TypeString, Size: 16},
		{Name: "cf", Type: field.TypeString, Size: 16},
		{Name: "active", Type: field.TypeBool, Default: true},
	}
	// CompaniesTable holds the schema information for the "companies" table.
	CompaniesTable = &schema.Table{
		Name:       "companies",
		Columns:    CompaniesColumns,
		PrimaryKey: []*schema.Column{CompaniesColumns[0]},
	}
	// ServiceCentersColumns holds the columns for the "service_centers" table.
	ServiceCentersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "codice", Type: field.TypeString, Unique: true, Size: 20},
		{Name: "nome", Type: field.TypeString, Size: 200},
		{Name: "active", Type: field.TypeBool, Default: true},
	}
	// ServiceCentersTable holds the schema information for the "service_centers" table.
	ServiceCentersTable = &schema.Table{
		Name:       "service_centers",
		Columns:    ServiceCentersColumns,
		PrimaryKey: []*schema.Column{ServiceCentersColumns[0]},
	}
	// TicketsColumns holds the columns for the "tickets" table.
	TicketsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "title", Type: field.TypeString, Size: 150},
		{Name: "question", Type: field.TypeString, Size: 2147483647},
		{Name: "state", Type: field.TypeEnum, Enums: []string{"OPEN", "CLOSED", "TODO", "WAIT"}, Default: "OPEN"},
		{Name: "priority", Type: field.TypeEnum, Enums: []string{"LOW", "MEDIUM", "HIGH"}, Default: "LOW"},
		{Name: "state_job", Type: field.TypeEnum, Enums: []string{"APERTA", "IN_ATTESA_CLIENTE", "PRESA_IN_CARICO", "IN_ATTESA_CENTRO_SERVIZI", "CHIUSA"}, Default: "APERTA"},
		{Name: "data_assigned", Type: field.TypeTime, Nullable: true},
		{Name: "data_creation", Type: field.TypeTime},
		{Name: "data_updating", Type: field.TypeTime},
		{Name: "company_tickets", Type: field.TypeUUID},
		{Name: "service_center_tickets", Type: field.TypeUUID},
		{Name: "assigned_to_id", Type: field.TypeUUID, Nullable: true},
		{Name: "created_by_id", Type: field.TypeUUID},
		{Name: "updated_by_id", Type: field.TypeUUID, Nullable: true},
	}
	// TicketsTable holds the schema information for the "tickets" table.
	TicketsTable = &schema.Table{
		Name:       "tickets",
		Columns:    TicketsColumns,
		PrimaryKey: []*schema.Column{TicketsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "tickets_companies_tickets",
				Columns:    []*schema.Column{TicketsColumns[9]},
				RefColumns: []*schema.Column{CompaniesColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "tickets_service_centers_tickets",
				Columns:    []*schema.Column{TicketsColumns[10]},
				RefColumns: []*schema.Column{ServiceCentersColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "tickets_users_assigned_tickets",
				Columns:    []*schema.Column{TicketsColumns[11]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "tickets_users_created_tickets",
				Columns:    []*schema.Column{TicketsColumns[12]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "tickets_users_updated_tickets",
				Columns:    []*schema.Column{TicketsColumns[13]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "keycloak_id", Type: field.TypeString, Unique: true},
		{Name: "username", Type: field.TypeString, Size: 150},
		{Name: "email", Type: field.TypeString, Size: 255},
		{Name: "first_name", Type: field.TypeString, Nullable: true, Size: 100},
		{Name: "last_name", Type: field.TypeString, Nullable: true, Size: 100},
		{Name: "role", Type: field.TypeEnum, Enums: []string{"customer", "support_l1", "support_l2", "supervisor"}},
		{Name: "active", Type: field.TypeBool, Default: true},
		{Name: "company_users", Type: field.TypeUUID, Nullable: true},
		{Name: "service_center_users", Type: field.TypeUUID, Nullable: true},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "users_companies_users",
				Columns:    []*schema.Column{UsersColumns[8]},
				RefColumns: []*schema.Column{CompaniesColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "users_service_centers_users",
				Columns:    []*schema.Column{UsersColumns[9]},
				RefColumns: []*schema.Column{ServiceCentersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AttachmentsTable,
		CommentsTable,
		CompaniesTable,
		ServiceCentersTable,
		TicketsTable,
		UsersTable,
	}
)

func init() {
	AttachmentsTable.ForeignKeys[0].RefTable = CommentsTable
	AttachmentsTable.ForeignKeys[1].RefTable = TicketsTable
	AttachmentsTable.ForeignKeys[2].RefTable = UsersTable
	CommentsTable.ForeignKeys[0].RefTable = TicketsTable
	CommentsTable.ForeignKeys[1].RefTable = UsersTable
	TicketsTable.ForeignKeys[0].RefTable = CompaniesTable
	TicketsTable.ForeignKeys[1].RefTable = ServiceCentersTable
	TicketsTable.ForeignKeys[2].RefTable = UsersTable
	TicketsTable.ForeignKeys[3].RefTable = UsersTable
	TicketsTable.ForeignKeys[4].RefTable = UsersTable
	UsersTable.ForeignKeys[0].RefTable = CompaniesTable
	UsersTable.ForeignKeys[1].RefTable = ServiceCentersTable
}
