// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"ticket-service/ent/attachment"
	"ticket-service/ent/comment"
	"ticket-service/ent/ticket"
	"ticket-service/ent/user"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// AttachmentCreate is the builder for creating a Attachment entity.
type AttachmentCreate struct {
	config
	mutation *AttachmentMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (ac *AttachmentCreate) SetName(s string) *AttachmentCreate {
	ac.mutation.SetName(s)
	return ac
}

// SetPath sets the "path" field.
func (ac *AttachmentCreate) SetPath(s string) *AttachmentCreate {
	ac.mutation.SetPath(s)
	return ac
}

// SetMimeType sets the "mime_type" field.
func (ac *AttachmentCreate) SetMimeType(s string) *AttachmentCreate {
	ac.mutation.SetMimeType(s)
	return ac
}

// SetNillableMimeType sets the "mime_type" field if the given value is not nil.
func (ac *AttachmentCreate) SetNillableMimeType(s *string) *AttachmentCreate {
	if s != nil {
		ac.SetMimeType(*s)
	}
	return ac
}

// SetSizeBytes sets the "size_bytes" field.
func (ac *AttachmentCreate) SetSizeBytes(i int64) *AttachmentCreate {
	ac.mutation.SetSizeBytes(i)
	return ac
}

// SetNillableSizeBytes sets the "size_bytes" field if the given value is not nil.
func (ac *AttachmentCreate) SetNillableSizeBytes(i *int64) *AttachmentCreate {
	if i != nil {
		ac.SetSizeBytes(*i)
	}
	return ac
}

// SetUploadedAt sets the "uploaded_at" field.
func (ac *AttachmentCreate) SetUploadedAt(t time.Time) *AttachmentCreate {
	ac.mutation.SetUploadedAt(t)
	return ac
}

// SetNillableUploadedAt sets the "uploaded_at" field if the given value is not nil.
func (ac *AttachmentCreate) SetNillableUploadedAt(t *time.Time) *AttachmentCreate {
	if t != nil {
		ac.SetUploadedAt(*t)
	}
	return ac
}

// SetID sets the "id" field.
func (ac *AttachmentCreate) SetID(u uuid.UUID) *AttachmentCreate {
	ac.mutation.SetID(u)
	return ac
}

// SetNillableID sets the "id" field if the given value is not nil.
func (ac *AttachmentCreate) SetNillableID(u *uuid.UUID) *AttachmentCreate {
	if u != nil {
		ac.SetID(*u)
	}
	return ac
}

// SetTicketID sets the "ticket" edge to the Ticket entity by ID.
func (ac *AttachmentCreate) SetTicketID(id uuid.UUID) *AttachmentCreate {
	ac.mutation.SetTicketID(id)
	return ac
}

// SetNillableTicketID sets the "ticket" edge to the Ticket entity by ID if the given value is not nil.
func (ac *AttachmentCreate) SetNillableTicketID(id *uuid.UUID) *AttachmentCreate {
	if id != nil {
		ac = ac.SetTicketID(*id)
	}
	return ac
}

// SetTicket sets the "ticket" edge to the Ticket entity.
func (ac *AttachmentCreate) SetTicket(t *Ticket) *AttachmentCreate {
	return ac.SetTicketID(t.ID)
}

// SetCommentID sets the "comment" edge to the Comment entity by ID.
func (ac *AttachmentCreate) SetCommentID(id uuid.UUID) *AttachmentCreate {
	ac.mutation.SetCommentID(id)
	return ac
}

// SetNillableCommentID sets the "comment" edge to the Comment entity by ID if the given value is not nil.
func (ac *AttachmentCreate) SetNillableCommentID(id *uuid.UUID) *AttachmentCreate {
	if id != nil {
		ac = ac.SetCommentID(*id)
	}
	return ac
}

// SetComment sets the "comment" edge to the Comment entity.
func (ac *AttachmentCreate) SetComment(c *Comment) *AttachmentCreate {
	return ac.SetCommentID(c.ID)
}

// SetUploadedByID sets the "uploaded_by" edge to the User entity by ID.
func (ac *AttachmentCreate) SetUploadedByID(id uuid.UUID) *AttachmentCreate {
	ac.mutation.SetUploadedByID(id)
	return ac
}

// SetNillableUploadedByID sets the "uploaded_by" edge to the User entity by ID if the given value is not nil.
func (ac *AttachmentCreate) SetNillableUploadedByID(id *uuid.UUID) *AttachmentCreate {
	if id != nil {
		ac = ac.SetUploadedByID(*id)
	}
	return ac
}

// SetUploadedBy sets the "uploaded_by" edge to the User entity.
func (ac *AttachmentCreate) SetUploadedBy(u *User) *AttachmentCreate {
	return ac.SetUploadedByID(u.ID)
}

// Mutation returns the AttachmentMutation object of the builder.
func (ac *AttachmentCreate) Mutation() *AttachmentMutation {
	return ac.mutation
}

// Save creates the Attachment in the database.
func (ac *AttachmentCreate) Save(ctx context.Context) (*Attachment, error) {
	ac.defaults()
	return withHooks(ctx, ac.sqlSave, ac.mutation, ac.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (ac *AttachmentCreate) SaveX(ctx context.Context) *Attachment {
	v, err := ac.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ac *AttachmentCreate) Exec(ctx context.Context) error {
	_, err := ac.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ac *AttachmentCreate) ExecX(ctx context.Context) {
	if err := ac.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ac *AttachmentCreate) defaults() {
	if _, ok := ac.mutation.UploadedAt(); !ok {
		v := attachment.DefaultUploadedAt()
		ac.mutation.SetUploadedAt(v)
	}
	if _, ok := ac.mutation.ID(); !ok {
		v := attachment.DefaultID()
		ac.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ac *AttachmentCreate) check() error {
	if _, ok := ac.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Attachment.name"`)}
	}
	if v, ok := ac.mutation.Name(); ok {
		if err := attachment.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Attachment.name": %w`, err)}
		}
	}
	if _, ok := ac.mutation.Path(); !ok {
		return &ValidationError{Name: "path", err: errors.New(`ent: missing required field "Attachment.path"`)}
	}
	if v, ok := ac.mutation.Path(); ok {
		if err := attachment.PathValidator(v); err != nil {
			return &ValidationError{Name: "path", err: fmt.Errorf(`ent: validator failed for field "Attachment.path": %w`, err)}
		}
	}
	if v, ok := ac.mutation.MimeType(); ok {
		if err := attachment.MimeTypeValidator(v); err != nil {
			return &ValidationError{Name: "mime_type", err: fmt.Errorf(`ent: validator failed for field "Attachment.mime_type": %w`, err)}
		}
	}
	if _, ok := ac.mutation.UploadedAt(); !ok {
		return &ValidationError{Name: "uploaded_at", err: errors.New(`ent: missing required field "Attachment.uploaded_at"`)}
	}
	return nil
}

func (ac *AttachmentCreate) sqlSave(ctx context.Context) (*Attachment, error) {
	if err := ac.check(); err != nil {
		return nil, err
	}
	_node, _spec := ac.createSpec()
	if err := sqlgraph.CreateNode(ctx, ac.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	ac.mutation.id = &_node.ID
	ac.mutation.done = true
	return _node, nil
}

func (ac *AttachmentCreate) createSpec() (*Attachment, *sqlgraph.CreateSpec) {
	var (
		_node = &Attachment{config: ac.config}
		_spec = sqlgraph.NewCreateSpec(attachment.Table, sqlgraph.NewFieldSpec(attachment.FieldID, field.TypeUUID))
	)
	if id, ok := ac.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := ac.mutation.Name(); ok {
		_spec.SetField(attachment.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := ac.mutation.Path(); ok {
		_spec.SetField(attachment.FieldPath, field.TypeString, value)
		_node.Path = value
	}
	if value, ok := ac.mutation.MimeType(); ok {
		_spec.SetField(attachment.FieldMimeType, field.TypeString, value)
		_node.MimeType = value
	}
	if value, ok := ac.mutation.SizeBytes(); ok {
		_spec.SetField(attachment.FieldSizeBytes, field.TypeInt64, value)
		_node.SizeBytes = value
	}
	if value, ok := ac.mutation.UploadedAt(); ok {
		_spec.SetField(attachment.FieldUploadedAt, field.TypeTime, value)
		_node.UploadedAt = value
	}
	if nodes := ac.mutation.TicketIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   attachment.TicketTable,
			Columns: []string{attachment.TicketColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticket.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ticket_attachments = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := ac.mutation.CommentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   attachment.CommentTable,
			Columns: []string{attachment.CommentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(comment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.comment_attachments = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := ac.mutation.UploadedByIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   attachment.UploadedByTable,
			Columns: []string{attachment.UploadedByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_attachments = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// AttachmentCreateBulk is the builder for creating many Attachment entities in bulk.
type AttachmentCreateBulk struct {
	config
	err      error
	builders []*AttachmentCreate
}

// Save creates the Attachment entities in the database.
func (acb *AttachmentCreateBulk) Save(ctx context.Context) ([]*Attachment, error) {
	if acb.err != nil {
		return nil, acb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(acb.builders))
	nodes := make([]*Attachment, len(acb.builders))
	mutators := make([]Mutator, len(acb.builders))
	for i := range acb.builders {
		func(i int, root context.Context) {
			builder := acb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AttachmentMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, acb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, acb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, acb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (acb *AttachmentCreateBulk) SaveX(ctx context.Context) []*Attachment {
	v, err := acb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (acb *AttachmentCreateBulk) Exec(ctx context.Context) error {
	_, err := acb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (acb *AttachmentCreateBulk) ExecX(ctx context.Context) {
	if err := acb.Exec(ctx); err != nil {
		panic(err)
	}
}
