// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"ticket-service/ent/attachment"
	"ticket-service/ent/comment"
	"ticket-service/ent/predicate"
	"ticket-service/ent/ticket"
	"ticket-service/ent/user"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// CommentUpdate is the builder for updating Comment entities.
type CommentUpdate struct {
	config
	hooks    []Hook
	mutation *CommentMutation
}

// Where appends a list predicates to the CommentUpdate builder.
func (cu *CommentUpdate) Where(ps ...predicate.Comment) *CommentUpdate {
	cu.mutation.Where(ps...)
	return cu
}

// SetOrderComment sets the "order_comment" field.
func (cu *CommentUpdate) SetOrderComment(i int) *CommentUpdate {
	cu.mutation.ResetOrderComment()
	cu.mutation.SetOrderComment(i)
	return cu
}

// SetNillableOrderComment sets the "order_comment" field if the given value is not nil.
func (cu *CommentUpdate) SetNillableOrderComment(i *int) *CommentUpdate {
	if i != nil {
		cu.SetOrderComment(*i)
	}
	return cu
}

// AddOrderComment adds i to the "order_comment" field.
func (cu *CommentUpdate) AddOrderComment(i int) *CommentUpdate {
	cu.mutation.AddOrderComment(i)
	return cu
}

// SetCommentDetail sets the "comment_detail" field.
func (cu *CommentUpdate) SetCommentDetail(s string) *CommentUpdate {
	cu.mutation.SetCommentDetail(s)
	return cu
}

// SetNillableCommentDetail sets the "comment_detail" field if the given value is not nil.
func (cu *CommentUpdate) SetNillableCommentDetail(s *string) *CommentUpdate {
	if s != nil {
		cu.SetCommentDetail(*s)
	}
	return cu
}

// SetTicketID sets the "ticket" edge to the Ticket entity by ID.
func (cu *CommentUpdate) SetTicketID(id uuid.UUID) *CommentUpdate {
	cu.mutation.SetTicketID(id)
	return cu
}

// SetTicket sets the "ticket" edge to the Ticket entity.
func (cu *CommentUpdate) SetTicket(t *Ticket) *CommentUpdate {
	return cu.SetTicketID(t.ID)
}

// SetAuthorID sets the "author" edge to the User entity by ID.
func (cu *CommentUpdate) SetAuthorID(id uuid.UUID) *CommentUpdate {
	cu.mutation.SetAuthorID(id)
	return cu
}

// SetAuthor sets the "author" edge to the User entity.
func (cu *CommentUpdate) SetAuthor(u *User) *CommentUpdate {
	return cu.SetAuthorID(u.ID)
}

// AddAttachmentIDs adds the "attachments" edge to the Attachment entity by IDs.
func (cu *CommentUpdate) AddAttachmentIDs(ids ...uuid.UUID) *CommentUpdate {
	cu.mutation.AddAttachmentIDs(ids...)
	return cu
}

// AddAttachments adds the "attachments" edges to the Attachment entity.
func (cu *CommentUpdate) AddAttachments(a ...*Attachment) *CommentUpdate {
	ids := make([]uuid.UUID, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return cu.AddAttachmentIDs(ids...)
}

// Mutation returns the CommentMutation object of the builder.
func (cu *CommentUpdate) Mutation() *CommentMutation {
	return cu.mutation
}

// ClearTicket clears the "ticket" edge to the Ticket entity.
func (cu *CommentUpdate) ClearTicket() *CommentUpdate {
	cu.mutation.ClearTicket()
	return cu
}

// ClearAuthor clears the "author" edge to the User entity.
func (cu *CommentUpdate) ClearAuthor() *CommentUpdate {
	cu.mutation.ClearAuthor()
	return cu
}

// ClearAttachments clears all "attachments" edges to the Attachment entity.
func (cu *CommentUpdate) ClearAttachments() *CommentUpdate {
	cu.mutation.ClearAttachments()
	return cu
}

// RemoveAttachmentIDs removes the "attachments" edge to Attachment entities by IDs.
func (cu *CommentUpdate) RemoveAttachmentIDs(ids ...uuid.UUID) *CommentUpdate {
	cu.mutation.RemoveAttachmentIDs(ids...)
	return cu
}

// RemoveAttachments removes "attachments" edges to Attachment entities.
func (cu *CommentUpdate) RemoveAttachments(a ...*Attachment) *CommentUpdate {
	ids := make([]uuid.UUID, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return cu.RemoveAttachmentIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (cu *CommentUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, cu.sqlSave, cu.mutation, cu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (cu *CommentUpdate) SaveX(ctx context.Context) int {
	affected, err := cu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (cu *CommentUpdate) Exec(ctx context.Context) error {
	_, err := cu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cu *CommentUpdate) ExecX(ctx context.Context) {
	if err := cu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cu *CommentUpdate) check() error {
	if v, ok := cu.mutation.OrderComment(); ok {
		if err := comment.OrderCommentValidator(v); err != nil {
			return &ValidationError{Name: "order_comment", err: fmt.Errorf(`ent: validator failed for field "Comment.order_comment": %w`, err)}
		}
	}
	if cu.mutation.TicketCleared() && len(cu.mutation.TicketIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Comment.ticket"`)
	}
	if cu.mutation.AuthorCleared() && len(cu.mutation.AuthorIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Comment.author"`)
	}
	return nil
}

func (cu *CommentUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := cu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(comment.Table, comment.Columns, sqlgraph.NewFieldSpec(comment.FieldID, field.TypeUUID))
	if ps := cu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cu.mutation.OrderComment(); ok {
		_spec.SetField(comment.FieldOrderComment, field.TypeInt, value)
	}
	if value, ok := cu.mutation.AddedOrderComment(); ok {
		_spec.AddField(comment.FieldOrderComment, field.TypeInt, value)
	}
	if value, ok := cu.mutation.CommentDetail(); ok {
		_spec.SetField(comment.FieldCommentDetail, field.TypeString, value)
	}
	if cu.mutation.TicketCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   comment.TicketTable,
			Columns: []string{comment.TicketColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticket.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.TicketIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   comment.TicketTable,
			Columns: []string{comment.TicketColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticket.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if cu.mutation.AuthorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   comment.AuthorTable,
			Columns: []string{comment.AuthorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.AuthorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   comment.AuthorTable,
			Columns: []string{comment.AuthorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if cu.mutation.AttachmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   comment.AttachmentsTable,
			Columns: []string{comment.AttachmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attachment.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.RemovedAttachmentsIDs(); len(nodes) > 0 && !cu.mutation.AttachmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   comment.AttachmentsTable,
			Columns: []string{comment.AttachmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attachment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.AttachmentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   comment.AttachmentsTable,
			Columns: []string{comment.AttachmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attachment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, cu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{comment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	cu.mutation.done = true
	return n, nil
}

// CommentUpdateOne is the builder for updating a single Comment entity.
type CommentUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CommentMutation
}

// SetOrderComment sets the "order_comment" field.
func (cuo *CommentUpdateOne) SetOrderComment(i int) *CommentUpdateOne {
	cuo.mutation.ResetOrderComment()
	cuo.mutation.SetOrderComment(i)
	return cuo
}

// SetNillableOrderComment sets the "order_comment" field if the given value is not nil.
func (cuo *CommentUpdateOne) SetNillableOrderComment(i *int) *CommentUpdateOne {
	if i != nil {
		cuo.SetOrderComment(*i)
	}
	return cuo
}

// AddOrderComment adds i to the "order_comment" field.
func (cuo *CommentUpdateOne) AddOrderComment(i int) *CommentUpdateOne {
	cuo.mutation.AddOrderComment(i)
	return cuo
}

// SetCommentDetail sets the "comment_detail" field.
func (cuo *CommentUpdateOne) SetCommentDetail(s string) *CommentUpdateOne {
	cuo.mutation.SetCommentDetail(s)
	return cuo
}

// SetNillableCommentDetail sets the "comment_detail" field if the given value is not nil.
func (cuo *CommentUpdateOne) SetNillableCommentDetail(s *string) *CommentUpdateOne {
	if s != nil {
		cuo.SetCommentDetail(*s)
	}
	return cuo
}

// SetTicketID sets the "ticket" edge to the Ticket entity by ID.
func (cuo *CommentUpdateOne) SetTicketID(id uuid.UUID) *CommentUpdateOne {
	cuo.mutation.SetTicketID(id)
	return cuo
}

// SetTicket sets the "ticket" edge to the Ticket entity.
func (cuo *CommentUpdateOne) SetTicket(t *Ticket) *CommentUpdateOne {
	return cuo.SetTicketID(t.ID)
}

// SetAuthorID sets the "author" edge to the User entity by ID.
func (cuo *CommentUpdateOne) SetAuthorID(id uuid.UUID) *CommentUpdateOne {
	cuo.mutation.SetAuthorID(id)
	return cuo
}

// SetAuthor sets the "author" edge to the User entity.
func (cuo *CommentUpdateOne) SetAuthor(u *User) *CommentUpdateOne {
	return cuo.SetAuthorID(u.ID)
}

// AddAttachmentIDs adds the "attachments" edge to the Attachment entity by IDs.
func (cuo *CommentUpdateOne) AddAttachmentIDs(ids ...uuid.UUID) *CommentUpdateOne {
	cuo.mutation.AddAttachmentIDs(ids...)
	return cuo
}

// AddAttachments adds the "attachments" edges to the Attachment entity.
func (cuo *CommentUpdateOne) AddAttachments(a ...*Attachment) *CommentUpdateOne {
	ids := make([]uuid.UUID, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return cuo.AddAttachmentIDs(ids...)
}

// Mutation returns the CommentMutation object of the builder.
func (cuo *CommentUpdateOne) Mutation() *CommentMutation {
	return cuo.mutation
}

// ClearTicket clears the "ticket" edge to the Ticket entity.
func (cuo *CommentUpdateOne) ClearTicket() *CommentUpdateOne {
	cuo.mutation.ClearTicket()
	return cuo
}

// ClearAuthor clears the "author" edge to the User entity.
func (cuo *CommentUpdateOne) ClearAuthor() *CommentUpdateOne {
	cuo.mutation.ClearAuthor()
	return cuo
}

// ClearAttachments clears all "attachments" edges to the Attachment entity.
func (cuo *CommentUpdateOne) ClearAttachments() *CommentUpdateOne {
	cuo.mutation.ClearAttachments()
	return cuo
}

// RemoveAttachmentIDs removes the "attachments" edge to Attachment entities by IDs.
func (cuo *CommentUpdateOne) RemoveAttachmentIDs(ids ...uuid.UUID) *CommentUpdateOne {
	cuo.mutation.RemoveAttachmentIDs(ids...)
	return cuo
}

// RemoveAttachments removes "attachments" edges to Attachment entities.
func (cuo *CommentUpdateOne) RemoveAttachments(a ...*Attachment) *CommentUpdateOne {
	ids := make([]uuid.UUID, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return cuo.RemoveAttachmentIDs(ids...)
}

// Where appends a list predicates to the CommentUpdate builder.
func (cuo *CommentUpdateOne) Where(ps ...predicate.Comment) *CommentUpdateOne {
	cuo.mutation.Where(ps...)
	return cuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (cuo *CommentUpdateOne) Select(field string, fields ...string) *CommentUpdateOne {
	cuo.fields = append([]string{field}, fields...)
	return cuo
}

// Save executes the query and returns the updated Comment entity.
func (cuo *CommentUpdateOne) Save(ctx context.Context) (*Comment, error) {
	return withHooks(ctx, cuo.sqlSave, cuo.mutation, cuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (cuo *CommentUpdateOne) SaveX(ctx context.Context) *Comment {
	node, err := cuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (cuo *CommentUpdateOne) Exec(ctx context.Context) error {
	_, err := cuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cuo *CommentUpdateOne) ExecX(ctx context.Context) {
	if err := cuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cuo *CommentUpdateOne) check() error {
	if v, ok := cuo.mutation.OrderComment(); ok {
		if err := comment.OrderCommentValidator(v); err != nil {
			return &ValidationError{Name: "order_comment", err: fmt.Errorf(`ent: validator failed for field "Comment.order_comment": %w`, err)}
		}
	}
	if cuo.mutation.TicketCleared() && len(cuo.mutation.TicketIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Comment.ticket"`)
	}
	if cuo.mutation.AuthorCleared() && len(cuo.mutation.AuthorIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Comment.author"`)
	}
	return nil
}

func (cuo *CommentUpdateOne) sqlSave(ctx context.Context) (_node *Comment, err error) {
	if err := cuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(comment.Table, comment.Columns, sqlgraph.NewFieldSpec(comment.FieldID, field.TypeUUID))
	id, ok := cuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Comment.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := cuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, comment.FieldID)
		for _, f := range fields {
			if !comment.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != comment.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := cuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cuo.mutation.OrderComment(); ok {
		_spec.SetField(comment.FieldOrderComment, field.TypeInt, value)
	}
	if value, ok := cuo.mutation.AddedOrderComment(); ok {
		_spec.AddField(comment.FieldOrderComment, field.TypeInt, value)
	}
	if value, ok := cuo.mutation.CommentDetail(); ok {
		_spec.SetField(comment.FieldCommentDetail, field.TypeString, value)
	}
	if cuo.mutation.TicketCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   comment.TicketTable,
			Columns: []string{comment.TicketColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticket.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.TicketIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   comment.TicketTable,
			Columns: []string{comment.TicketColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticket.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if cuo.mutation.AuthorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   comment.AuthorTable,
			Columns: []string{comment.AuthorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.AuthorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   comment.AuthorTable,
			Columns: []string{comment.AuthorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if cuo.mutation.AttachmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   comment.AttachmentsTable,
			Columns: []string{comment.AttachmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attachment.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.RemovedAttachmentsIDs(); len(nodes) > 0 && !cuo.mutation.AttachmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   comment.AttachmentsTable,
			Columns: []string{comment.AttachmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attachment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.AttachmentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   comment.AttachmentsTable,
			Columns: []string{comment.AttachmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attachment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Comment{config: cuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, cuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{comment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	cuo.mutation.done = true
	return _node, nil
}
