// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"ticket-service/ent/company"
	"ticket-service/ent/predicate"
	"ticket-service/ent/ticket"
	"ticket-service/ent/user"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// CompanyUpdate is the builder for updating Company entities.
type CompanyUpdate struct {
	config
	hooks    []Hook
	mutation *CompanyMutation
}

// Where appends a list predicates to the CompanyUpdate builder.
func (cu *CompanyUpdate) Where(ps ...predicate.Company) *CompanyUpdate {
	cu.mutation.Where(ps...)
	return cu
}

// SetCodice sets the "codice" field.
func (cu *CompanyUpdate) SetCodice(s string) *CompanyUpdate {
	cu.mutation.SetCodice(s)
	return cu
}

// SetNillableCodice sets the "codice" field if the given value is not nil.
func (cu *CompanyUpdate) SetNillableCodice(s *string) *CompanyUpdate {
	if s != nil {
		cu.SetCodice(*s)
	}
	return cu
}

// SetRagioneSociale sets the "ragione_sociale" field.
func (cu *CompanyUpdate) SetRagioneSociale(s string) *CompanyUpdate {
	cu.mutation.SetRagioneSociale(s)
	return cu
}

// SetNillableRagioneSociale sets the "ragione_sociale" field if the given value is not nil.
func (cu *CompanyUpdate) SetNillableRagioneSociale(s *string) *CompanyUpdate {
	if s != nil {
		cu.SetRagioneSociale(*s)
	}
	return cu
}

// SetPiva sets the "piva" field.
func (cu *CompanyUpdate) SetPiva(s string) *CompanyUpdate {
	cu.mutation.SetPiva(s)
	return cu
}

// SetNillablePiva sets the "piva" field if the given value is not nil.
func (cu *CompanyUpdate) SetNillablePiva(s *string) *CompanyUpdate {
	if s != nil {
		cu.SetPiva(*s)
	}
	return cu
}

// SetCf sets the "cf" field.
func (cu *CompanyUpdate) SetCf(s string) *CompanyUpdate {
	cu.mutation.SetCf(s)
	return cu
}

// SetNillableCf sets the "cf" field if the given value is not nil.
func (cu *CompanyUpdate) SetNillableCf(s *string) *CompanyUpdate {
	if s != nil {
		cu.SetCf(*s)
	}
	return cu
}

// SetActive sets the "active" field.
func (cu *CompanyUpdate) SetActive(b bool) *CompanyUpdate {
	cu.mutation.SetActive(b)
	return cu
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (cu *CompanyUpdate) SetNillableActive(b *bool) *CompanyUpdate {
	if b != nil {
		cu.SetActive(*b)
	}
	return cu
}

// AddUserIDs adds the "users" edge to the User entity by IDs.
func (cu *CompanyUpdate) AddUserIDs(ids ...uuid.UUID) *CompanyUpdate {
	cu.mutation.AddUserIDs(ids...)
	return cu
}

// AddUsers adds the "users" edges to the User entity.
func (cu *CompanyUpdate) AddUsers(u ...*User) *CompanyUpdate {
	ids := make([]uuid.UUID, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return cu.AddUserIDs(ids...)
}

// AddTicketIDs adds the "tickets" edge to the Ticket entity by IDs.
func (cu *CompanyUpdate) AddTicketIDs(ids ...uuid.UUID) *CompanyUpdate {
	cu.mutation.AddTicketIDs(ids...)
	return cu
}

// AddTickets adds the "tickets" edges to the Ticket entity.
func (cu *CompanyUpdate) AddTickets(t ...*Ticket) *CompanyUpdate {
	ids := make([]uuid.UUID, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return cu.AddTicketIDs(ids...)
}

// Mutation returns the CompanyMutation object of the builder.
func (cu *CompanyUpdate) Mutation() *CompanyMutation {
	return cu.mutation
}

// ClearUsers clears all "users" edges to the User entity.
func (cu *CompanyUpdate) ClearUsers() *CompanyUpdate {
	cu.mutation.ClearUsers()
	return cu
}

// RemoveUserIDs removes the "users" edge to User entities by IDs.
func (cu *CompanyUpdate) RemoveUserIDs(ids ...uuid.UUID) *CompanyUpdate {
	cu.mutation.RemoveUserIDs(ids...)
	return cu
}

// RemoveUsers removes "users" edges to User entities.
func (cu *CompanyUpdate) RemoveUsers(u ...*User) *CompanyUpdate {
	ids := make([]uuid.UUID, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return cu.RemoveUserIDs(ids...)
}

// ClearTickets clears all "tickets" edges to the Ticket entity.
func (cu *CompanyUpdate) ClearTickets() *CompanyUpdate {
	cu.mutation.ClearTickets()
	return cu
}

// RemoveTicketIDs removes the "tickets" edge to Ticket entities by IDs.
func (cu *CompanyUpdate) RemoveTicketIDs(ids ...uuid.UUID) *CompanyUpdate {
	cu.mutation.RemoveTicketIDs(ids...)
	return cu
}

// RemoveTickets removes "tickets" edges to Ticket entities.
func (cu *CompanyUpdate) RemoveTickets(t ...*Ticket) *CompanyUpdate {
	ids := make([]uuid.UUID, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return cu.RemoveTicketIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (cu *CompanyUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, cu.sqlSave, cu.mutation, cu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (cu *CompanyUpdate) SaveX(ctx context.Context) int {
	affected, err := cu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (cu *CompanyUpdate) Exec(ctx context.Context) error {
	_, err := cu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cu *CompanyUpdate) ExecX(ctx context.Context) {
	if err := cu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cu *CompanyUpdate) check() error {
	if v, ok := cu.mutation.Codice(); ok {
		if err := company.CodiceValidator(v); err != nil {
			return &ValidationError{Name: "codice", err: fmt.Errorf(`ent: validator failed for field "Company.codice": %w`, err)}
		}
	}
	if v, ok := cu.mutation.RagioneSociale(); ok {
		if err := company.RagioneSocialeValidator(v); err != nil {
			return &ValidationError{Name: "ragione_sociale", err: fmt.Errorf(`ent: validator failed for field "Company.ragione_sociale": %w`, err)}
		}
	}
	if v, ok := cu.mutation.Piva(); ok {
		if err := company.PivaValidator(v); err != nil {
			return &ValidationError{Name: "piva", err: fmt.Errorf(`ent: validator failed for field "Company.piva": %w`, err)}
		}
	}
	if v, ok := cu.mutation.Cf(); ok {
		if err := company.CfValidator(v); err != nil {
			return &ValidationError{Name: "cf", err: fmt.Errorf(`ent: validator failed for field "Company.cf": %w`, err)}
		}
	}
	return nil
}

func (cu *CompanyUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := cu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(company.Table, company.Columns, sqlgraph.NewFieldSpec(company.FieldID, field.TypeUUID))
	if ps := cu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cu.mutation.Codice(); ok {
		_spec.SetField(company.FieldCodice, field.TypeString, value)
	}
	if value, ok := cu.mutation.RagioneSociale(); ok {
		_spec.SetField(company.FieldRagioneSociale, field.TypeString, value)
	}
	if value, ok := cu.mutation.Piva(); ok {
		_spec.SetField(company.FieldPiva, field.TypeString, value)
	}
	if value, ok := cu.mutation.Cf(); ok {
		_spec.SetField(company.FieldCf, field.TypeString, value)
	}
	if value, ok := cu.mutation.Active(); ok {
		_spec.SetField(company.FieldActive, field.TypeBool, value)
	}
	if cu.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   company.UsersTable,
			Columns: []string{company.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.RemovedUsersIDs(); len(nodes) > 0 && !cu.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   company.UsersTable,
			Columns: []string{company.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   company.UsersTable,
			Columns: []string{company.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if cu.mutation.TicketsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   company.TicketsTable,
			Columns: []string{company.TicketsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticket.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.RemovedTicketsIDs(); len(nodes) > 0 && !cu.mutation.TicketsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   company.TicketsTable,
			Columns: []string{company.TicketsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticket.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.TicketsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   company.TicketsTable,
			Columns: []string{company.TicketsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticket.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, cu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{company.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	cu.mutation.done = true
	return n, nil
}

// CompanyUpdateOne is the builder for updating a single Company entity.
type CompanyUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CompanyMutation
}

// SetCodice sets the "codice" field.
func (cuo *CompanyUpdateOne) SetCodice(s string) *CompanyUpdateOne {
	cuo.mutation.SetCodice(s)
	return cuo
}

// SetNillableCodice sets the "codice" field if the given value is not nil.
func (cuo *CompanyUpdateOne) SetNillableCodice(s *string) *CompanyUpdateOne {
	if s != nil {
		cuo.SetCodice(*s)
	}
	return cuo
}

// SetRagioneSociale sets the "ragione_sociale" field.
func (cuo *CompanyUpdateOne) SetRagioneSociale(s string) *CompanyUpdateOne {
	cuo.mutation.SetRagioneSociale(s)
	return cuo
}

// SetNillableRagioneSociale sets the "ragione_sociale" field if the given value is not nil.
func (cuo *CompanyUpdateOne) SetNillableRagioneSociale(s *string) *CompanyUpdateOne {
	if s != nil {
		cuo.SetRagioneSociale(*s)
	}
	return cuo
}

// SetPiva sets the "piva" field.
func (cuo *CompanyUpdateOne) SetPiva(s string) *CompanyUpdateOne {
	cuo.mutation.SetPiva(s)
	return cuo
}

// SetNillablePiva sets the "piva" field if the given value is not nil.
func (cuo *CompanyUpdateOne) SetNillablePiva(s *string) *CompanyUpdateOne {
	if s != nil {
		cuo.SetPiva(*s)
	}
	return cuo
}

// SetCf sets the "cf" field.
func (cuo *CompanyUpdateOne) SetCf(s string) *CompanyUpdateOne {
	cuo.mutation.SetCf(s)
	return cuo
}

// SetNillableCf sets the "cf" field if the given value is not nil.
func (cuo *CompanyUpdateOne) SetNillableCf(s *string) *CompanyUpdateOne {
	if s != nil {
		cuo.SetCf(*s)
	}
	return cuo
}

// SetActive sets the "active" field.
func (cuo *CompanyUpdateOne) SetActive(b bool) *CompanyUpdateOne {
	cuo.mutation.SetActive(b)
	return cuo
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (cuo *CompanyUpdateOne) SetNillableActive(b *bool) *CompanyUpdateOne {
	if b != nil {
		cuo.SetActive(*b)
	}
	return cuo
}

// AddUserIDs adds the "users" edge to the User entity by IDs.
func (cuo *CompanyUpdateOne) AddUserIDs(ids ...uuid.UUID) *CompanyUpdateOne {
	cuo.mutation.AddUserIDs(ids...)
	return cuo
}

// AddUsers adds the "users" edges to the User entity.
func (cuo *CompanyUpdateOne) AddUsers(u ...*User) *CompanyUpdateOne {
	ids := make([]uuid.UUID, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return cuo.AddUserIDs(ids...)
}

// AddTicketIDs adds the "tickets" edge to the Ticket entity by IDs.
func (cuo *CompanyUpdateOne) AddTicketIDs(ids ...uuid.UUID) *CompanyUpdateOne {
	cuo.mutation.AddTicketIDs(ids...)
	return cuo
}

// AddTickets adds the "tickets" edges to the Ticket entity.
func (cuo *CompanyUpdateOne) AddTickets(t ...*Ticket) *CompanyUpdateOne {
	ids := make([]uuid.UUID, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return cuo.AddTicketIDs(ids...)
}

// Mutation returns the CompanyMutation object of the builder.
func (cuo *CompanyUpdateOne) Mutation() *CompanyMutation {
	return cuo.mutation
}

// ClearUsers clears all "users" edges to the User entity.
func (cuo *CompanyUpdateOne) ClearUsers() *CompanyUpdateOne {
	cuo.mutation.ClearUsers()
	return cuo
}

// RemoveUserIDs removes the "users" edge to User entities by IDs.
func (cuo *CompanyUpdateOne) RemoveUserIDs(ids ...uuid.UUID) *CompanyUpdateOne {
	cuo.mutation.RemoveUserIDs(ids...)
	return cuo
}

// RemoveUsers removes "users" edges to User entities.
func (cuo *CompanyUpdateOne) RemoveUsers(u ...*User) *CompanyUpdateOne {
	ids := make([]uuid.UUID, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return cuo.RemoveUserIDs(ids...)
}

// ClearTickets clears all "tickets" edges to the Ticket entity.
func (cuo *CompanyUpdateOne) ClearTickets() *CompanyUpdateOne {
	cuo.mutation.ClearTickets()
	return cuo
}

// RemoveTicketIDs removes the "tickets" edge to Ticket entities by IDs.
func (cuo *CompanyUpdateOne) RemoveTicketIDs(ids ...uuid.UUID) *CompanyUpdateOne {
	cuo.mutation.RemoveTicketIDs(ids...)
	return cuo
}

// RemoveTickets removes "tickets" edges to Ticket entities.
func (cuo *CompanyUpdateOne) RemoveTickets(t ...*Ticket) *CompanyUpdateOne {
	ids := make([]uuid.UUID, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return cuo.RemoveTicketIDs(ids...)
}

// Where appends a list predicates to the CompanyUpdate builder.
func (cuo *CompanyUpdateOne) Where(ps ...predicate.Company) *CompanyUpdateOne {
	cuo.mutation.Where(ps...)
	return cuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (cuo *CompanyUpdateOne) Select(field string, fields ...string) *CompanyUpdateOne {
	cuo.fields = append([]string{field}, fields...)
	return cuo
}

// Save executes the query and returns the updated Company entity.
func (cuo *CompanyUpdateOne) Save(ctx context.Context) (*Company, error) {
	return withHooks(ctx, cuo.sqlSave, cuo.mutation, cuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (cuo *CompanyUpdateOne) SaveX(ctx context.Context) *Company {
	node, err := cuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (cuo *CompanyUpdateOne) Exec(ctx context.Context) error {
	_, err := cuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cuo *CompanyUpdateOne) ExecX(ctx context.Context) {
	if err := cuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cuo *CompanyUpdateOne) check() error {
	if v, ok := cuo.mutation.Codice(); ok {
		if err := company.CodiceValidator(v); err != nil {
			return &ValidationError{Name: "codice", err: fmt.Errorf(`ent: validator failed for field "Company.codice": %w`, err)}
		}
	}
	if v, ok := cuo.mutation.RagioneSociale(); ok {
		if err := company.RagioneSocialeValidator(v); err != nil {
			return &ValidationError{Name: "ragione_sociale", err: fmt.Errorf(`ent: validator failed for field "Company.ragione_sociale": %w`, err)}
		}
	}
	if v, ok := cuo.mutation.Piva(); ok {
		if err := company.PivaValidator(v); err != nil {
			return &ValidationError{Name: "piva", err: fmt.Errorf(`ent: validator failed for field "Company.piva": %w`, err)}
		}
	}
	if v, ok := cuo.mutation.Cf(); ok {
		if err := company.CfValidator(v); err != nil {
			return &ValidationError{Name: "cf", err: fmt.Errorf(`ent: validator failed for field "Company.cf": %w`, err)}
		}
	}
	return nil
}

func (cuo *CompanyUpdateOne) sqlSave(ctx context.Context) (_node *Company, err error) {
	if err := cuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(company.Table, company.Columns, sqlgraph.NewFieldSpec(company.FieldID, field.TypeUUID))
	id, ok := cuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Company.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := cuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, company.FieldID)
		for _, f := range fields {
			if !company.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != company.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := cuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cuo.mutation.Codice(); ok {
		_spec.SetField(company.FieldCodice, field.TypeString, value)
	}
	if value, ok := cuo.mutation.RagioneSociale(); ok {
		_spec.SetField(company.FieldRagioneSociale, field.TypeString, value)
	}
	if value, ok := cuo.mutation.Piva(); ok {
		_spec.SetField(company.FieldPiva, field.TypeString, value)
	}
	if value, ok := cuo.mutation.Cf(); ok {
		_spec.SetField(company.FieldCf, field.TypeString, value)
	}
	if value, ok := cuo.mutation.Active(); ok {
		_spec.SetField(company.FieldActive, field.TypeBool, value)
	}
	if cuo.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   company.UsersTable,
			Columns: []string{company.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.RemovedUsersIDs(); len(nodes) > 0 && !cuo.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   company.UsersTable,
			Columns: []string{company.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   company.UsersTable,
			Columns: []string{company.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if cuo.mutation.TicketsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   company.TicketsTable,
			Columns: []string{company.TicketsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticket.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.RemovedTicketsIDs(); len(nodes) > 0 && !cuo.mutation.TicketsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   company.TicketsTable,
			Columns: []string{company.TicketsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticket.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.TicketsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   company.TicketsTable,
			Columns: []string{company.TicketsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticket.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Company{config: cuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, cuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{company.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	cuo.mutation.done = true
	return _node, nil
}
