// Code generated by ent, DO NOT EDIT.

package ent

import (
	"ticket-service/ent/attachment"
	"ticket-service/ent/comment"
	"ticket-service/ent/company"
	"ticket-service/ent/schema"
	"ticket-service/ent/servicecenter"
	"ticket-service/ent/ticket"
	"ticket-service/ent/user"
	"time"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	attachmentFields := schema.Attachment{}.Fields()
	_ = attachmentFields
	// attachmentDescName is the schema descriptor for name field.
	attachmentDescName := attachmentFields[1].Descriptor()
	// attachment.NameValidator is a validator for the "name" field. It is called by the builders before save.
	attachment.NameValidator = attachmentDescName.Validators[0].(func(string) error)
	// attachmentDescPath is the schema descriptor for path field.
	attachmentDescPath := attachmentFields[2].Descriptor()
	// attachment.PathValidator is a validator for the "path" field. It is called by the builders before save.
	attachment.PathValidator = attachmentDescPath.Validators[0].(func(string) error)
	// attachmentDescMimeType is the schema descriptor for mime_type field.
	attachmentDescMimeType := attachmentFields[3].Descriptor()
	// attachment.MimeTypeValidator is a validator for the "mime_type" field. It is called by the builders before save.
	attachment.MimeTypeValidator = attachmentDescMimeType.Validators[0].(func(string) error)
	// attachmentDescUploadedAt is the schema descriptor for uploaded_at field.
	attachmentDescUploadedAt := attachmentFields[5].Descriptor()
	// attachment.DefaultUploadedAt holds the default value on creation for the uploaded_at field.
	attachment.DefaultUploadedAt = attachmentDescUploadedAt.Default.(func() time.Time)
	// attachmentDescID is the schema descriptor for id field.
	attachmentDescID := attachmentFields[0].Descriptor()
	// attachment.DefaultID holds the default value on creation for the id field.
	attachment.DefaultID = attachmentDescID.Default.(func() uuid.UUID)
	commentFields := schema.Comment{}.Fields()
	_ = commentFields
	// commentDescOrderComment is the schema descriptor for order_comment field.
	commentDescOrderComment := commentFields[1].Descriptor()
	// comment.OrderCommentValidator is a validator for the "order_comment" field. It is called by the builders before save.
	comment.OrderCommentValidator = commentDescOrderComment.Validators[0].(func(int) error)
	// commentDescDataCreation is the schema descriptor for data_creation field.
	commentDescDataCreation := commentFields[3].Descriptor()
	// comment.DefaultDataCreation holds the default value on creation for the data_creation field.
	comment.DefaultDataCreation = commentDescDataCreation.Default.(func() time.Time)
	// commentDescID is the schema descriptor for id field.
	commentDescID := commentFields[0].Descriptor()
	// comment.DefaultID holds the default value on creation for the id field.
	comment.DefaultID = commentDescID.Default.(func() uuid.UUID)
	companyFields := schema.Company{}.Fields()
	_ = companyFields
	// companyDescCodice is the schema descriptor for codice field.
	companyDescCodice := companyFields[1].Descriptor()
	// company.CodiceValidator is a validator for the "codice" field. It is called by the builders before save.
	company.CodiceValidator = companyDescCodice.Validators[0].(func(string) error)
	// companyDescRagioneSociale is the schema descriptor for ragione_sociale field.
	companyDescRagioneSociale := companyFields[2].Descriptor()
	// company.RagioneSocialeValidator is a validator for the "ragione_sociale" field. It is called by the builders before save.
	company.RagioneSocialeValidator = companyDescRagioneSociale.Validators[0].(func(string) error)
	// companyDescPiva is the schema descriptor for piva field.
	companyDescPiva := companyFields[3].Descriptor()
	// company.PivaValidator is a validator for the "piva" field. It is called by the builders before save.
	company.PivaValidator = companyDescPiva.Validators[0].(func(string) error)
	// companyDescCf is the schema descriptor for cf field.
	companyDescCf := companyFields[4].Descriptor()
	// company.CfValidator is a validator for the "cf" field. It is called by the builders before save.
	company.CfValidator = companyDescCf.Validators[0].(func(string) error)
	// companyDescActive is the schema descriptor for active field.
	companyDescActive := companyFields[5].Descriptor()
	// company.DefaultActive holds the default value on creation for the active field.
	company.DefaultActive = companyDescActive.Default.(bool)
	// companyDescID is the schema descriptor for id field.
	companyDescID := companyFields[0].Descriptor()
	// company.DefaultID holds the default value on creation for the id field.
	company.DefaultID = companyDescID.Default.(func() uuid.UUID)
	servicecenterFields := schema.ServiceCenter{}.Fields()
	_ = servicecenterFields
	// servicecenterDescCodice is the schema descriptor for codice field.
	servicecenterDescCodice := servicecenterFields[1].Descriptor()
	// servicecenter.CodiceValidator is a validator for the "codice" field. It is called by the builders before save.
	servicecenter.CodiceValidator = servicecenterDescCodice.Validators[0].(func(string) error)
	// servicecenterDescNome is the schema descriptor for nome field.
	servicecenterDescNome := servicecenterFields[2].Descriptor()
	// servicecenter.NomeValidator is a validator for the "nome" field. It is called by the builders before save.
	servicecenter.NomeValidator = servicecenterDescNome.Validators[0].(func(string) error)
	// servicecenterDescActive is the schema descriptor for active field.
	servicecenterDescActive := servicecenterFields[3].Descriptor()
	// servicecenter.DefaultActive holds the default value on creation for the active field.
	servicecenter.DefaultActive = servicecenterDescActive.Default.(bool)
	// servicecenterDescID is the schema descriptor for id field.
	servicecenterDescID := servicecenterFields[0].Descriptor()
	// servicecenter.DefaultID holds the default value on creation for the id field.
	servicecenter.DefaultID = servicecenterDescID.Default.(func() uuid.UUID)
	ticketFields := schema.Ticket{}.Fields()
	_ = ticketFields
	// ticketDescTitle is the schema descriptor for title field.
	ticketDescTitle := ticketFields[1].Descriptor()
	// ticket.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	ticket.TitleValidator = ticketDescTitle.Validators[0].(func(string) error)
	// ticketDescDataCreation is the schema descriptor for data_creation field.
	ticketDescDataCreation := ticketFields[7].Descriptor()
	// ticket.DefaultDataCreation holds the default value on creation for the data_creation field.
	ticket.DefaultDataCreation = ticketDescDataCreation.Default.(func() time.Time)
	// ticketDescDataUpdating is the schema descriptor for data_updating field.
	ticketDescDataUpdating := ticketFields[8].Descriptor()
	// ticket.DefaultDataUpdating holds the default value on creation for the data_updating field.
	ticket.DefaultDataUpdating = ticketDescDataUpdating.Default.(func() time.Time)
	// ticket.UpdateDefaultDataUpdating holds the default value on update for the data_updating field.
	ticket.UpdateDefaultDataUpdating = ticketDescDataUpdating.UpdateDefault.(func() time.Time)
	// ticketDescID is the schema descriptor for id field.
	ticketDescID := ticketFields[0].Descriptor()
	// ticket.DefaultID holds the default value on creation for the id field.
	ticket.DefaultID = ticketDescID.Default.(func() uuid.UUID)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescUsername is the schema descriptor for username field.
	userDescUsername := userFields[2].Descriptor()
	// user.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	user.UsernameValidator = userDescUsername.Validators[0].(func(string) error)
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[3].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescFirstName is the schema descriptor for first_name field.
	userDescFirstName := userFields[4].Descriptor()
	// user.FirstNameValidator is a validator for the "first_name" field. It is called by the builders before save.
	user.FirstNameValidator = userDescFirstName.Validators[0].(func(string) error)
	// userDescLastName is the schema descriptor for last_name field.
	userDescLastName := userFields[5].Descriptor()
	// user.LastNameValidator is a validator for the "last_name" field. It is called by the builders before save.
	user.LastNameValidator = userDescLastName.Validators[0].(func(string) error)
	// userDescActive is the schema descriptor for active field.
	userDescActive := userFields[7].Descriptor()
	// user.DefaultActive holds the default value on creation for the active field.
	user.DefaultActive = userDescActive.Default.(bool)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
}
