// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"ticket-service/ent/predicate"
	"ticket-service/ent/servicecenter"
	"ticket-service/ent/ticket"
	"ticket-service/ent/user"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// ServiceCenterUpdate is the builder for updating ServiceCenter entities.
type ServiceCenterUpdate struct {
	config
	hooks    []Hook
	mutation *ServiceCenterMutation
}

// Where appends a list predicates to the ServiceCenterUpdate builder.
func (scu *ServiceCenterUpdate) Where(ps ...predicate.ServiceCenter) *ServiceCenterUpdate {
	scu.mutation.Where(ps...)
	return scu
}

// SetCodice sets the "codice" field.
func (scu *ServiceCenterUpdate) SetCodice(s string) *ServiceCenterUpdate {
	scu.mutation.SetCodice(s)
	return scu
}

// SetNillableCodice sets the "codice" field if the given value is not nil.
func (scu *ServiceCenterUpdate) SetNillableCodice(s *string) *ServiceCenterUpdate {
	if s != nil {
		scu.SetCodice(*s)
	}
	return scu
}

// SetNome sets the "nome" field.
func (scu *ServiceCenterUpdate) SetNome(s string) *ServiceCenterUpdate {
	scu.mutation.SetNome(s)
	return scu
}

// SetNillableNome sets the "nome" field if the given value is not nil.
func (scu *ServiceCenterUpdate) SetNillableNome(s *string) *ServiceCenterUpdate {
	if s != nil {
		scu.SetNome(*s)
	}
	return scu
}

// SetActive sets the "active" field.
func (scu *ServiceCenterUpdate) SetActive(b bool) *ServiceCenterUpdate {
	scu.mutation.SetActive(b)
	return scu
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (scu *ServiceCenterUpdate) SetNillableActive(b *bool) *ServiceCenterUpdate {
	if b != nil {
		scu.SetActive(*b)
	}
	return scu
}

// AddUserIDs adds the "users" edge to the User entity by IDs.
func (scu *ServiceCenterUpdate) AddUserIDs(ids ...uuid.UUID) *ServiceCenterUpdate {
	scu.mutation.AddUserIDs(ids...)
	return scu
}

// AddUsers adds the "users" edges to the User entity.
func (scu *ServiceCenterUpdate) AddUsers(u ...*User) *ServiceCenterUpdate {
	ids := make([]uuid.UUID, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return scu.AddUserIDs(ids...)
}

// AddTicketIDs adds the "tickets" edge to the Ticket entity by IDs.
func (scu *ServiceCenterUpdate) AddTicketIDs(ids ...uuid.UUID) *ServiceCenterUpdate {
	scu.mutation.AddTicketIDs(ids...)
	return scu
}

// AddTickets adds the "tickets" edges to the Ticket entity.
func (scu *ServiceCenterUpdate) AddTickets(t ...*Ticket) *ServiceCenterUpdate {
	ids := make([]uuid.UUID, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return scu.AddTicketIDs(ids...)
}

// Mutation returns the ServiceCenterMutation object of the builder.
func (scu *ServiceCenterUpdate) Mutation() *ServiceCenterMutation {
	return scu.mutation
}

// ClearUsers clears all "users" edges to the User entity.
func (scu *ServiceCenterUpdate) ClearUsers() *ServiceCenterUpdate {
	scu.mutation.ClearUsers()
	return scu
}

// RemoveUserIDs removes the "users" edge to User entities by IDs.
func (scu *ServiceCenterUpdate) RemoveUserIDs(ids ...uuid.UUID) *ServiceCenterUpdate {
	scu.mutation.RemoveUserIDs(ids...)
	return scu
}

// RemoveUsers removes "users" edges to User entities.
func (scu *ServiceCenterUpdate) RemoveUsers(u ...*User) *ServiceCenterUpdate {
	ids := make([]uuid.UUID, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return scu.RemoveUserIDs(ids...)
}

// ClearTickets clears all "tickets" edges to the Ticket entity.
func (scu *ServiceCenterUpdate) ClearTickets() *ServiceCenterUpdate {
	scu.mutation.ClearTickets()
	return scu
}

// RemoveTicketIDs removes the "tickets" edge to Ticket entities by IDs.
func (scu *ServiceCenterUpdate) RemoveTicketIDs(ids ...uuid.UUID) *ServiceCenterUpdate {
	scu.mutation.RemoveTicketIDs(ids...)
	return scu
}

// RemoveTickets removes "tickets" edges to Ticket entities.
func (scu *ServiceCenterUpdate) RemoveTickets(t ...*Ticket) *ServiceCenterUpdate {
	ids := make([]uuid.UUID, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return scu.RemoveTicketIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (scu *ServiceCenterUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, scu.sqlSave, scu.mutation, scu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (scu *ServiceCenterUpdate) SaveX(ctx context.Context) int {
	affected, err := scu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (scu *ServiceCenterUpdate) Exec(ctx context.Context) error {
	_, err := scu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (scu *ServiceCenterUpdate) ExecX(ctx context.Context) {
	if err := scu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (scu *ServiceCenterUpdate) check() error {
	if v, ok := scu.mutation.Codice(); ok {
		if err := servicecenter.CodiceValidator(v); err != nil {
			return &ValidationError{Name: "codice", err: fmt.Errorf(`ent: validator failed for field "ServiceCenter.codice": %w`, err)}
		}
	}
	if v, ok := scu.mutation.Nome(); ok {
		if err := servicecenter.NomeValidator(v); err != nil {
			return &ValidationError{Name: "nome", err: fmt.Errorf(`ent: validator failed for field "ServiceCenter.nome": %w`, err)}
		}
	}
	return nil
}

func (scu *ServiceCenterUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := scu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(servicecenter.Table, servicecenter.Columns, sqlgraph.NewFieldSpec(servicecenter.FieldID, field.TypeUUID))
	if ps := scu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := scu.mutation.Codice(); ok {
		_spec.SetField(servicecenter.FieldCodice, field.TypeString, value)
	}
	if value, ok := scu.mutation.Nome(); ok {
		_spec.SetField(servicecenter.FieldNome, field.TypeString, value)
	}
	if value, ok := scu.mutation.Active(); ok {
		_spec.SetField(servicecenter.FieldActive, field.TypeBool, value)
	}
	if scu.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   servicecenter.UsersTable,
			Columns: []string{servicecenter.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := scu.mutation.RemovedUsersIDs(); len(nodes) > 0 && !scu.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   servicecenter.UsersTable,
			Columns: []string{servicecenter.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := scu.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   servicecenter.UsersTable,
			Columns: []string{servicecenter.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if scu.mutation.TicketsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   servicecenter.TicketsTable,
			Columns: []string{servicecenter.TicketsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticket.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := scu.mutation.RemovedTicketsIDs(); len(nodes) > 0 && !scu.mutation.TicketsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   servicecenter.TicketsTable,
			Columns: []string{servicecenter.TicketsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticket.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := scu.mutation.TicketsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   servicecenter.TicketsTable,
			Columns: []string{servicecenter.TicketsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticket.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, scu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{servicecenter.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	scu.mutation.done = true
	return n, nil
}

// ServiceCenterUpdateOne is the builder for updating a single ServiceCenter entity.
type ServiceCenterUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ServiceCenterMutation
}

// SetCodice sets the "codice" field.
func (scuo *ServiceCenterUpdateOne) SetCodice(s string) *ServiceCenterUpdateOne {
	scuo.mutation.SetCodice(s)
	return scuo
}

// SetNillableCodice sets the "codice" field if the given value is not nil.
func (scuo *ServiceCenterUpdateOne) SetNillableCodice(s *string) *ServiceCenterUpdateOne {
	if s != nil {
		scuo.SetCodice(*s)
	}
	return scuo
}

// SetNome sets the "nome" field.
func (scuo *ServiceCenterUpdateOne) SetNome(s string) *ServiceCenterUpdateOne {
	scuo.mutation.SetNome(s)
	return scuo
}

// SetNillableNome sets the "nome" field if the given value is not nil.
func (scuo *ServiceCenterUpdateOne) SetNillableNome(s *string) *ServiceCenterUpdateOne {
	if s != nil {
		scuo.SetNome(*s)
	}
	return scuo
}

// SetActive sets the "active" field.
func (scuo *ServiceCenterUpdateOne) SetActive(b bool) *ServiceCenterUpdateOne {
	scuo.mutation.SetActive(b)
	return scuo
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (scuo *ServiceCenterUpdateOne) SetNillableActive(b *bool) *ServiceCenterUpdateOne {
	if b != nil {
		scuo.SetActive(*b)
	}
	return scuo
}

// AddUserIDs adds the "users" edge to the User entity by IDs.
func (scuo *ServiceCenterUpdateOne) AddUserIDs(ids ...uuid.UUID) *ServiceCenterUpdateOne {
	scuo.mutation.AddUserIDs(ids...)
	return scuo
}

// AddUsers adds the "users" edges to the User entity.
func (scuo *ServiceCenterUpdateOne) AddUsers(u ...*User) *ServiceCenterUpdateOne {
	ids := make([]uuid.UUID, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return scuo.AddUserIDs(ids...)
}

// AddTicketIDs adds the "tickets" edge to the Ticket entity by IDs.
func (scuo *ServiceCenterUpdateOne) AddTicketIDs(ids ...uuid.UUID) *ServiceCenterUpdateOne {
	scuo.mutation.AddTicketIDs(ids...)
	return scuo
}

// AddTickets adds the "tickets" edges to the Ticket entity.
func (scuo *ServiceCenterUpdateOne) AddTickets(t ...*Ticket) *ServiceCenterUpdateOne {
	ids := make([]uuid.UUID, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return scuo.AddTicketIDs(ids...)
}

// Mutation returns the ServiceCenterMutation object of the builder.
func (scuo *ServiceCenterUpdateOne) Mutation() *ServiceCenterMutation {
	return scuo.mutation
}

// ClearUsers clears all "users" edges to the User entity.
func (scuo *ServiceCenterUpdateOne) ClearUsers() *ServiceCenterUpdateOne {
	scuo.mutation.ClearUsers()
	return scuo
}

// RemoveUserIDs removes the "users" edge to User entities by IDs.
func (scuo *ServiceCenterUpdateOne) RemoveUserIDs(ids ...uuid.UUID) *ServiceCenterUpdateOne {
	scuo.mutation.RemoveUserIDs(ids...)
	return scuo
}

// RemoveUsers removes "users" edges to User entities.
func (scuo *ServiceCenterUpdateOne) RemoveUsers(u ...*User) *ServiceCenterUpdateOne {
	ids := make([]uuid.UUID, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return scuo.RemoveUserIDs(ids...)
}

// ClearTickets clears all "tickets" edges to the Ticket entity.
func (scuo *ServiceCenterUpdateOne) ClearTickets() *ServiceCenterUpdateOne {
	scuo.mutation.ClearTickets()
	return scuo
}

// RemoveTicketIDs removes the "tickets" edge to Ticket entities by IDs.
func (scuo *ServiceCenterUpdateOne) RemoveTicketIDs(ids ...uuid.UUID) *ServiceCenterUpdateOne {
	scuo.mutation.RemoveTicketIDs(ids...)
	return scuo
}

// RemoveTickets removes "tickets" edges to Ticket entities.
func (scuo *ServiceCenterUpdateOne) RemoveTickets(t ...*Ticket) *ServiceCenterUpdateOne {
	ids := make([]uuid.UUID, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return scuo.RemoveTicketIDs(ids...)
}

// Where appends a list predicates to the ServiceCenterUpdate builder.
func (scuo *ServiceCenterUpdateOne) Where(ps ...predicate.ServiceCenter) *ServiceCenterUpdateOne {
	scuo.mutation.Where(ps...)
	return scuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (scuo *ServiceCenterUpdateOne) Select(field string, fields ...string) *ServiceCenterUpdateOne {
	scuo.fields = append([]string{field}, fields...)
	return scuo
}

// Save executes the query and returns the updated ServiceCenter entity.
func (scuo *ServiceCenterUpdateOne) Save(ctx context.Context) (*ServiceCenter, error) {
	return withHooks(ctx, scuo.sqlSave, scuo.mutation, scuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (scuo *ServiceCenterUpdateOne) SaveX(ctx context.Context) *ServiceCenter {
	node, err := scuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (scuo *ServiceCenterUpdateOne) Exec(ctx context.Context) error {
	_, err := scuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (scuo *ServiceCenterUpdateOne) ExecX(ctx context.Context) {
	if err := scuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (scuo *ServiceCenterUpdateOne) check() error {
	if v, ok := scuo.mutation.Codice(); ok {
		if err := servicecenter.CodiceValidator(v); err != nil {
			return &ValidationError{Name: "codice", err: fmt.Errorf(`ent: validator failed for field "ServiceCenter.codice": %w`, err)}
		}
	}
	if v, ok := scuo.mutation.Nome(); ok {
		if err := servicecenter.NomeValidator(v); err != nil {
			return &ValidationError{Name: "nome", err: fmt.Errorf(`ent: validator failed for field "ServiceCenter.nome": %w`, err)}
		}
	}
	return nil
}

func (scuo *ServiceCenterUpdateOne) sqlSave(ctx context.Context) (_node *ServiceCenter, err error) {
	if err := scuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(servicecenter.Table, servicecenter.Columns, sqlgraph.NewFieldSpec(servicecenter.FieldID, field.TypeUUID))
	id, ok := scuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ServiceCenter.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := scuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, servicecenter.FieldID)
		for _, f := range fields {
			if !servicecenter.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != servicecenter.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := scuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := scuo.mutation.Codice(); ok {
		_spec.SetField(servicecenter.FieldCodice, field.TypeString, value)
	}
	if value, ok := scuo.mutation.Nome(); ok {
		_spec.SetField(servicecenter.FieldNome, field.TypeString, value)
	}
	if value, ok := scuo.mutation.Active(); ok {
		_spec.SetField(servicecenter.FieldActive, field.TypeBool, value)
	}
	if scuo.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   servicecenter.UsersTable,
			Columns: []string{servicecenter.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := scuo.mutation.RemovedUsersIDs(); len(nodes) > 0 && !scuo.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   servicecenter.UsersTable,
			Columns: []string{servicecenter.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := scuo.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   servicecenter.UsersTable,
			Columns: []string{servicecenter.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if scuo.mutation.TicketsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   servicecenter.TicketsTable,
			Columns: []string{servicecenter.TicketsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticket.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := scuo.mutation.RemovedTicketsIDs(); len(nodes) > 0 && !scuo.mutation.TicketsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   servicecenter.TicketsTable,
			Columns: []string{servicecenter.TicketsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticket.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := scuo.mutation.TicketsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   servicecenter.TicketsTable,
			Columns: []string{servicecenter.TicketsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticket.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ServiceCenter{config: scuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, scuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{servicecenter.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	scuo.mutation.done = true
	return _node, nil
}
