// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"
	"ticket-service/ent/predicate"
	"ticket-service/ent/servicecenter"
	"ticket-service/ent/ticket"
	"ticket-service/ent/user"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// ServiceCenterQuery is the builder for querying ServiceCenter entities.
type ServiceCenterQuery struct {
	config
	ctx         *QueryContext
	order       []servicecenter.OrderOption
	inters      []Interceptor
	predicates  []predicate.ServiceCenter
	withUsers   *UserQuery
	withTickets *TicketQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ServiceCenterQuery builder.
func (scq *ServiceCenterQuery) Where(ps ...predicate.ServiceCenter) *ServiceCenterQuery {
	scq.predicates = append(scq.predicates, ps...)
	return scq
}

// Limit the number of records to be returned by this query.
func (scq *ServiceCenterQuery) Limit(limit int) *ServiceCenterQuery {
	scq.ctx.Limit = &limit
	return scq
}

// Offset to start from.
func (scq *ServiceCenterQuery) Offset(offset int) *ServiceCenterQuery {
	scq.ctx.Offset = &offset
	return scq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (scq *ServiceCenterQuery) Unique(unique bool) *ServiceCenterQuery {
	scq.ctx.Unique = &unique
	return scq
}

// Order specifies how the records should be ordered.
func (scq *ServiceCenterQuery) Order(o ...servicecenter.OrderOption) *ServiceCenterQuery {
	scq.order = append(scq.order, o...)
	return scq
}

// QueryUsers chains the current query on the "users" edge.
func (scq *ServiceCenterQuery) QueryUsers() *UserQuery {
	query := (&UserClient{config: scq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := scq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := scq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(servicecenter.Table, servicecenter.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, servicecenter.UsersTable, servicecenter.UsersColumn),
		)
		fromU = sqlgraph.SetNeighbors(scq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryTickets chains the current query on the "tickets" edge.
func (scq *ServiceCenterQuery) QueryTickets() *TicketQuery {
	query := (&TicketClient{config: scq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := scq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := scq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(servicecenter.Table, servicecenter.FieldID, selector),
			sqlgraph.To(ticket.Table, ticket.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, servicecenter.TicketsTable, servicecenter.TicketsColumn),
		)
		fromU = sqlgraph.SetNeighbors(scq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ServiceCenter entity from the query.
// Returns a *NotFoundError when no ServiceCenter was found.
func (scq *ServiceCenterQuery) First(ctx context.Context) (*ServiceCenter, error) {
	nodes, err := scq.Limit(1).All(setContextOp(ctx, scq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{servicecenter.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (scq *ServiceCenterQuery) FirstX(ctx context.Context) *ServiceCenter {
	node, err := scq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ServiceCenter ID from the query.
// Returns a *NotFoundError when no ServiceCenter ID was found.
func (scq *ServiceCenterQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = scq.Limit(1).IDs(setContextOp(ctx, scq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{servicecenter.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (scq *ServiceCenterQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := scq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ServiceCenter entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ServiceCenter entity is found.
// Returns a *NotFoundError when no ServiceCenter entities are found.
func (scq *ServiceCenterQuery) Only(ctx context.Context) (*ServiceCenter, error) {
	nodes, err := scq.Limit(2).All(setContextOp(ctx, scq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{servicecenter.Label}
	default:
		return nil, &NotSingularError{servicecenter.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (scq *ServiceCenterQuery) OnlyX(ctx context.Context) *ServiceCenter {
	node, err := scq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ServiceCenter ID in the query.
// Returns a *NotSingularError when more than one ServiceCenter ID is found.
// Returns a *NotFoundError when no entities are found.
func (scq *ServiceCenterQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = scq.Limit(2).IDs(setContextOp(ctx, scq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{servicecenter.Label}
	default:
		err = &NotSingularError{servicecenter.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (scq *ServiceCenterQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := scq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ServiceCenters.
func (scq *ServiceCenterQuery) All(ctx context.Context) ([]*ServiceCenter, error) {
	ctx = setContextOp(ctx, scq.ctx, ent.OpQueryAll)
	if err := scq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ServiceCenter, *ServiceCenterQuery]()
	return withInterceptors[[]*ServiceCenter](ctx, scq, qr, scq.inters)
}

// AllX is like All, but panics if an error occurs.
func (scq *ServiceCenterQuery) AllX(ctx context.Context) []*ServiceCenter {
	nodes, err := scq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ServiceCenter IDs.
func (scq *ServiceCenterQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if scq.ctx.Unique == nil && scq.path != nil {
		scq.Unique(true)
	}
	ctx = setContextOp(ctx, scq.ctx, ent.OpQueryIDs)
	if err = scq.Select(servicecenter.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (scq *ServiceCenterQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := scq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (scq *ServiceCenterQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, scq.ctx, ent.OpQueryCount)
	if err := scq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, scq, querierCount[*ServiceCenterQuery](), scq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (scq *ServiceCenterQuery) CountX(ctx context.Context) int {
	count, err := scq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (scq *ServiceCenterQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, scq.ctx, ent.OpQueryExist)
	switch _, err := scq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (scq *ServiceCenterQuery) ExistX(ctx context.Context) bool {
	exist, err := scq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ServiceCenterQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (scq *ServiceCenterQuery) Clone() *ServiceCenterQuery {
	if scq == nil {
		return nil
	}
	return &ServiceCenterQuery{
		config:      scq.config,
		ctx:         scq.ctx.Clone(),
		order:       append([]servicecenter.OrderOption{}, scq.order...),
		inters:      append([]Interceptor{}, scq.inters...),
		predicates:  append([]predicate.ServiceCenter{}, scq.predicates...),
		withUsers:   scq.withUsers.Clone(),
		withTickets: scq.withTickets.Clone(),
		// clone intermediate query.
		sql:  scq.sql.Clone(),
		path: scq.path,
	}
}

// WithUsers tells the query-builder to eager-load the nodes that are connected to
// the "users" edge. The optional arguments are used to configure the query builder of the edge.
func (scq *ServiceCenterQuery) WithUsers(opts ...func(*UserQuery)) *ServiceCenterQuery {
	query := (&UserClient{config: scq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	scq.withUsers = query
	return scq
}

// WithTickets tells the query-builder to eager-load the nodes that are connected to
// the "tickets" edge. The optional arguments are used to configure the query builder of the edge.
func (scq *ServiceCenterQuery) WithTickets(opts ...func(*TicketQuery)) *ServiceCenterQuery {
	query := (&TicketClient{config: scq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	scq.withTickets = query
	return scq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Codice string `json:"codice,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ServiceCenter.Query().
//		GroupBy(servicecenter.FieldCodice).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (scq *ServiceCenterQuery) GroupBy(field string, fields ...string) *ServiceCenterGroupBy {
	scq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ServiceCenterGroupBy{build: scq}
	grbuild.flds = &scq.ctx.Fields
	grbuild.label = servicecenter.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Codice string `json:"codice,omitempty"`
//	}
//
//	client.ServiceCenter.Query().
//		Select(servicecenter.FieldCodice).
//		Scan(ctx, &v)
func (scq *ServiceCenterQuery) Select(fields ...string) *ServiceCenterSelect {
	scq.ctx.Fields = append(scq.ctx.Fields, fields...)
	sbuild := &ServiceCenterSelect{ServiceCenterQuery: scq}
	sbuild.label = servicecenter.Label
	sbuild.flds, sbuild.scan = &scq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ServiceCenterSelect configured with the given aggregations.
func (scq *ServiceCenterQuery) Aggregate(fns ...AggregateFunc) *ServiceCenterSelect {
	return scq.Select().Aggregate(fns...)
}

func (scq *ServiceCenterQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range scq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, scq); err != nil {
				return err
			}
		}
	}
	for _, f := range scq.ctx.Fields {
		if !servicecenter.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if scq.path != nil {
		prev, err := scq.path(ctx)
		if err != nil {
			return err
		}
		scq.sql = prev
	}
	return nil
}

func (scq *ServiceCenterQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ServiceCenter, error) {
	var (
		nodes       = []*ServiceCenter{}
		_spec       = scq.querySpec()
		loadedTypes = [2]bool{
			scq.withUsers != nil,
			scq.withTickets != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ServiceCenter).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ServiceCenter{config: scq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, scq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := scq.withUsers; query != nil {
		if err := scq.loadUsers(ctx, query, nodes,
			func(n *ServiceCenter) { n.Edges.Users = []*User{} },
			func(n *ServiceCenter, e *User) { n.Edges.Users = append(n.Edges.Users, e) }); err != nil {
			return nil, err
		}
	}
	if query := scq.withTickets; query != nil {
		if err := scq.loadTickets(ctx, query, nodes,
			func(n *ServiceCenter) { n.Edges.Tickets = []*Ticket{} },
			func(n *ServiceCenter, e *Ticket) { n.Edges.Tickets = append(n.Edges.Tickets, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (scq *ServiceCenterQuery) loadUsers(ctx context.Context, query *UserQuery, nodes []*ServiceCenter, init func(*ServiceCenter), assign func(*ServiceCenter, *User)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*ServiceCenter)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.User(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(servicecenter.UsersColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.service_center_users
		if fk == nil {
			return fmt.Errorf(`foreign-key "service_center_users" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "service_center_users" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (scq *ServiceCenterQuery) loadTickets(ctx context.Context, query *TicketQuery, nodes []*ServiceCenter, init func(*ServiceCenter), assign func(*ServiceCenter, *Ticket)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*ServiceCenter)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Ticket(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(servicecenter.TicketsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.service_center_tickets
		if fk == nil {
			return fmt.Errorf(`foreign-key "service_center_tickets" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "service_center_tickets" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (scq *ServiceCenterQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := scq.querySpec()
	_spec.Node.Columns = scq.ctx.Fields
	if len(scq.ctx.Fields) > 0 {
		_spec.Unique = scq.ctx.Unique != nil && *scq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, scq.driver, _spec)
}

func (scq *ServiceCenterQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(servicecenter.Table, servicecenter.Columns, sqlgraph.NewFieldSpec(servicecenter.FieldID, field.TypeUUID))
	_spec.From = scq.sql
	if unique := scq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if scq.path != nil {
		_spec.Unique = true
	}
	if fields := scq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, servicecenter.FieldID)
		for i := range fields {
			if fields[i] != servicecenter.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := scq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := scq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := scq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := scq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (scq *ServiceCenterQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(scq.driver.Dialect())
	t1 := builder.Table(servicecenter.Table)
	columns := scq.ctx.Fields
	if len(columns) == 0 {
		columns = servicecenter.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if scq.sql != nil {
		selector = scq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if scq.ctx.Unique != nil && *scq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range scq.predicates {
		p(selector)
	}
	for _, p := range scq.order {
		p(selector)
	}
	if offset := scq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := scq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ServiceCenterGroupBy is the group-by builder for ServiceCenter entities.
type ServiceCenterGroupBy struct {
	selector
	build *ServiceCenterQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (scgb *ServiceCenterGroupBy) Aggregate(fns ...AggregateFunc) *ServiceCenterGroupBy {
	scgb.fns = append(scgb.fns, fns...)
	return scgb
}

// Scan applies the selector query and scans the result into the given value.
func (scgb *ServiceCenterGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, scgb.build.ctx, ent.OpQueryGroupBy)
	if err := scgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ServiceCenterQuery, *ServiceCenterGroupBy](ctx, scgb.build, scgb, scgb.build.inters, v)
}

func (scgb *ServiceCenterGroupBy) sqlScan(ctx context.Context, root *ServiceCenterQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(scgb.fns))
	for _, fn := range scgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*scgb.flds)+len(scgb.fns))
		for _, f := range *scgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*scgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := scgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ServiceCenterSelect is the builder for selecting fields of ServiceCenter entities.
type ServiceCenterSelect struct {
	*ServiceCenterQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (scs *ServiceCenterSelect) Aggregate(fns ...AggregateFunc) *ServiceCenterSelect {
	scs.fns = append(scs.fns, fns...)
	return scs
}

// Scan applies the selector query and scans the result into the given value.
func (scs *ServiceCenterSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, scs.ctx, ent.OpQuerySelect)
	if err := scs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ServiceCenterQuery, *ServiceCenterSelect](ctx, scs.ServiceCenterQuery, scs, scs.inters, v)
}

func (scs *ServiceCenterSelect) sqlScan(ctx context.Context, root *ServiceCenterQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(scs.fns))
	for _, fn := range scs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*scs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := scs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
