// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"ticket-service/ent/servicecenter"
	"ticket-service/ent/ticket"
	"ticket-service/ent/user"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// ServiceCenterCreate is the builder for creating a ServiceCenter entity.
type ServiceCenterCreate struct {
	config
	mutation *ServiceCenterMutation
	hooks    []Hook
}

// SetCodice sets the "codice" field.
func (scc *ServiceCenterCreate) SetCodice(s string) *ServiceCenterCreate {
	scc.mutation.SetCodice(s)
	return scc
}

// SetNome sets the "nome" field.
func (scc *ServiceCenterCreate) SetNome(s string) *ServiceCenterCreate {
	scc.mutation.SetNome(s)
	return scc
}

// SetActive sets the "active" field.
func (scc *ServiceCenterCreate) SetActive(b bool) *ServiceCenterCreate {
	scc.mutation.SetActive(b)
	return scc
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (scc *ServiceCenterCreate) SetNillableActive(b *bool) *ServiceCenterCreate {
	if b != nil {
		scc.SetActive(*b)
	}
	return scc
}

// SetID sets the "id" field.
func (scc *ServiceCenterCreate) SetID(u uuid.UUID) *ServiceCenterCreate {
	scc.mutation.SetID(u)
	return scc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (scc *ServiceCenterCreate) SetNillableID(u *uuid.UUID) *ServiceCenterCreate {
	if u != nil {
		scc.SetID(*u)
	}
	return scc
}

// AddUserIDs adds the "users" edge to the User entity by IDs.
func (scc *ServiceCenterCreate) AddUserIDs(ids ...uuid.UUID) *ServiceCenterCreate {
	scc.mutation.AddUserIDs(ids...)
	return scc
}

// AddUsers adds the "users" edges to the User entity.
func (scc *ServiceCenterCreate) AddUsers(u ...*User) *ServiceCenterCreate {
	ids := make([]uuid.UUID, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return scc.AddUserIDs(ids...)
}

// AddTicketIDs adds the "tickets" edge to the Ticket entity by IDs.
func (scc *ServiceCenterCreate) AddTicketIDs(ids ...uuid.UUID) *ServiceCenterCreate {
	scc.mutation.AddTicketIDs(ids...)
	return scc
}

// AddTickets adds the "tickets" edges to the Ticket entity.
func (scc *ServiceCenterCreate) AddTickets(t ...*Ticket) *ServiceCenterCreate {
	ids := make([]uuid.UUID, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return scc.AddTicketIDs(ids...)
}

// Mutation returns the ServiceCenterMutation object of the builder.
func (scc *ServiceCenterCreate) Mutation() *ServiceCenterMutation {
	return scc.mutation
}

// Save creates the ServiceCenter in the database.
func (scc *ServiceCenterCreate) Save(ctx context.Context) (*ServiceCenter, error) {
	scc.defaults()
	return withHooks(ctx, scc.sqlSave, scc.mutation, scc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (scc *ServiceCenterCreate) SaveX(ctx context.Context) *ServiceCenter {
	v, err := scc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (scc *ServiceCenterCreate) Exec(ctx context.Context) error {
	_, err := scc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (scc *ServiceCenterCreate) ExecX(ctx context.Context) {
	if err := scc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (scc *ServiceCenterCreate) defaults() {
	if _, ok := scc.mutation.Active(); !ok {
		v := servicecenter.DefaultActive
		scc.mutation.SetActive(v)
	}
	if _, ok := scc.mutation.ID(); !ok {
		v := servicecenter.DefaultID()
		scc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (scc *ServiceCenterCreate) check() error {
	if _, ok := scc.mutation.Codice(); !ok {
		return &ValidationError{Name: "codice", err: errors.New(`ent: missing required field "ServiceCenter.codice"`)}
	}
	if v, ok := scc.mutation.Codice(); ok {
		if err := servicecenter.CodiceValidator(v); err != nil {
			return &ValidationError{Name: "codice", err: fmt.Errorf(`ent: validator failed for field "ServiceCenter.codice": %w`, err)}
		}
	}
	if _, ok := scc.mutation.Nome(); !ok {
		return &ValidationError{Name: "nome", err: errors.New(`ent: missing required field "ServiceCenter.nome"`)}
	}
	if v, ok := scc.mutation.Nome(); ok {
		if err := servicecenter.NomeValidator(v); err != nil {
			return &ValidationError{Name: "nome", err: fmt.Errorf(`ent: validator failed for field "ServiceCenter.nome": %w`, err)}
		}
	}
	if _, ok := scc.mutation.Active(); !ok {
		return &ValidationError{Name: "active", err: errors.New(`ent: missing required field "ServiceCenter.active"`)}
	}
	return nil
}

func (scc *ServiceCenterCreate) sqlSave(ctx context.Context) (*ServiceCenter, error) {
	if err := scc.check(); err != nil {
		return nil, err
	}
	_node, _spec := scc.createSpec()
	if err := sqlgraph.CreateNode(ctx, scc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	scc.mutation.id = &_node.ID
	scc.mutation.done = true
	return _node, nil
}

func (scc *ServiceCenterCreate) createSpec() (*ServiceCenter, *sqlgraph.CreateSpec) {
	var (
		_node = &ServiceCenter{config: scc.config}
		_spec = sqlgraph.NewCreateSpec(servicecenter.Table, sqlgraph.NewFieldSpec(servicecenter.FieldID, field.TypeUUID))
	)
	if id, ok := scc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := scc.mutation.Codice(); ok {
		_spec.SetField(servicecenter.FieldCodice, field.TypeString, value)
		_node.Codice = value
	}
	if value, ok := scc.mutation.Nome(); ok {
		_spec.SetField(servicecenter.FieldNome, field.TypeString, value)
		_node.Nome = value
	}
	if value, ok := scc.mutation.Active(); ok {
		_spec.SetField(servicecenter.FieldActive, field.TypeBool, value)
		_node.Active = value
	}
	if nodes := scc.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   servicecenter.UsersTable,
			Columns: []string{servicecenter.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := scc.mutation.TicketsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   servicecenter.TicketsTable,
			Columns: []string{servicecenter.TicketsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticket.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ServiceCenterCreateBulk is the builder for creating many ServiceCenter entities in bulk.
type ServiceCenterCreateBulk struct {
	config
	err      error
	builders []*ServiceCenterCreate
}

// Save creates the ServiceCenter entities in the database.
func (sccb *ServiceCenterCreateBulk) Save(ctx context.Context) ([]*ServiceCenter, error) {
	if sccb.err != nil {
		return nil, sccb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(sccb.builders))
	nodes := make([]*ServiceCenter, len(sccb.builders))
	mutators := make([]Mutator, len(sccb.builders))
	for i := range sccb.builders {
		func(i int, root context.Context) {
			builder := sccb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ServiceCenterMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, sccb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, sccb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, sccb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (sccb *ServiceCenterCreateBulk) SaveX(ctx context.Context) []*ServiceCenter {
	v, err := sccb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (sccb *ServiceCenterCreateBulk) Exec(ctx context.Context) error {
	_, err := sccb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sccb *ServiceCenterCreateBulk) ExecX(ctx context.Context) {
	if err := sccb.Exec(ctx); err != nil {
		panic(err)
	}
}
