// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"ticket-service/ent/servicecenter"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// ServiceCenter is the model entity for the ServiceCenter schema.
type ServiceCenter struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Codice holds the value of the "codice" field.
	Codice string `json:"codice,omitempty"`
	// Nome holds the value of the "nome" field.
	Nome string `json:"nome,omitempty"`
	// Active holds the value of the "active" field.
	Active bool `json:"active,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ServiceCenterQuery when eager-loading is set.
	Edges        ServiceCenterEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ServiceCenterEdges holds the relations/edges for other nodes in the graph.
type ServiceCenterEdges struct {
	// Users holds the value of the users edge.
	Users []*User `json:"users,omitempty"`
	// Tickets holds the value of the tickets edge.
	Tickets []*Ticket `json:"tickets,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// UsersOrErr returns the Users value or an error if the edge
// was not loaded in eager-loading.
func (e ServiceCenterEdges) UsersOrErr() ([]*User, error) {
	if e.loadedTypes[0] {
		return e.Users, nil
	}
	return nil, &NotLoadedError{edge: "users"}
}

// TicketsOrErr returns the Tickets value or an error if the edge
// was not loaded in eager-loading.
func (e ServiceCenterEdges) TicketsOrErr() ([]*Ticket, error) {
	if e.loadedTypes[1] {
		return e.Tickets, nil
	}
	return nil, &NotLoadedError{edge: "tickets"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ServiceCenter) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case servicecenter.FieldActive:
			values[i] = new(sql.NullBool)
		case servicecenter.FieldCodice, servicecenter.FieldNome:
			values[i] = new(sql.NullString)
		case servicecenter.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ServiceCenter fields.
func (sc *ServiceCenter) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case servicecenter.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				sc.ID = *value
			}
		case servicecenter.FieldCodice:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field codice", values[i])
			} else if value.Valid {
				sc.Codice = value.String
			}
		case servicecenter.FieldNome:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field nome", values[i])
			} else if value.Valid {
				sc.Nome = value.String
			}
		case servicecenter.FieldActive:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field active", values[i])
			} else if value.Valid {
				sc.Active = value.Bool
			}
		default:
			sc.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ServiceCenter.
// This includes values selected through modifiers, order, etc.
func (sc *ServiceCenter) Value(name string) (ent.Value, error) {
	return sc.selectValues.Get(name)
}

// QueryUsers queries the "users" edge of the ServiceCenter entity.
func (sc *ServiceCenter) QueryUsers() *UserQuery {
	return NewServiceCenterClient(sc.config).QueryUsers(sc)
}

// QueryTickets queries the "tickets" edge of the ServiceCenter entity.
func (sc *ServiceCenter) QueryTickets() *TicketQuery {
	return NewServiceCenterClient(sc.config).QueryTickets(sc)
}

// Update returns a builder for updating this ServiceCenter.
// Note that you need to call ServiceCenter.Unwrap() before calling this method if this ServiceCenter
// was returned from a transaction, and the transaction was committed or rolled back.
func (sc *ServiceCenter) Update() *ServiceCenterUpdateOne {
	return NewServiceCenterClient(sc.config).UpdateOne(sc)
}

// Unwrap unwraps the ServiceCenter entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (sc *ServiceCenter) Unwrap() *ServiceCenter {
	_tx, ok := sc.config.driver.(*txDriver)
	if !ok {
		panic("ent: ServiceCenter is not a transactional entity")
	}
	sc.config.driver = _tx.drv
	return sc
}

// String implements the fmt.Stringer.
func (sc *ServiceCenter) String() string {
	var builder strings.Builder
	builder.WriteString("ServiceCenter(")
	builder.WriteString(fmt.Sprintf("id=%v, ", sc.ID))
	builder.WriteString("codice=")
	builder.WriteString(sc.Codice)
	builder.WriteString(", ")
	builder.WriteString("nome=")
	builder.WriteString(sc.Nome)
	builder.WriteString(", ")
	builder.WriteString("active=")
	builder.WriteString(fmt.Sprintf("%v", sc.Active))
	builder.WriteByte(')')
	return builder.String()
}

// ServiceCenters is a parsable slice of ServiceCenter.
type ServiceCenters []*ServiceCenter
