// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"ticket-service/ent/predicate"
	"ticket-service/ent/servicecenter"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ServiceCenterDelete is the builder for deleting a ServiceCenter entity.
type ServiceCenterDelete struct {
	config
	hooks    []Hook
	mutation *ServiceCenterMutation
}

// Where appends a list predicates to the ServiceCenterDelete builder.
func (scd *ServiceCenterDelete) Where(ps ...predicate.ServiceCenter) *ServiceCenterDelete {
	scd.mutation.Where(ps...)
	return scd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (scd *ServiceCenterDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, scd.sqlExec, scd.mutation, scd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (scd *ServiceCenterDelete) ExecX(ctx context.Context) int {
	n, err := scd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (scd *ServiceCenterDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(servicecenter.Table, sqlgraph.NewFieldSpec(servicecenter.FieldID, field.TypeUUID))
	if ps := scd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, scd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	scd.mutation.done = true
	return affected, err
}

// ServiceCenterDeleteOne is the builder for deleting a single ServiceCenter entity.
type ServiceCenterDeleteOne struct {
	scd *ServiceCenterDelete
}

// Where appends a list predicates to the ServiceCenterDelete builder.
func (scdo *ServiceCenterDeleteOne) Where(ps ...predicate.ServiceCenter) *ServiceCenterDeleteOne {
	scdo.scd.mutation.Where(ps...)
	return scdo
}

// Exec executes the deletion query.
func (scdo *ServiceCenterDeleteOne) Exec(ctx context.Context) error {
	n, err := scdo.scd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{servicecenter.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (scdo *ServiceCenterDeleteOne) ExecX(ctx context.Context) {
	if err := scdo.Exec(ctx); err != nil {
		panic(err)
	}
}
