// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"ticket-service/ent/company"
	"ticket-service/ent/servicecenter"
	"ticket-service/ent/ticket"
	"ticket-service/ent/user"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// Ticket is the model entity for the Ticket schema.
type Ticket struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// Question holds the value of the "question" field.
	Question string `json:"question,omitempty"`
	// State holds the value of the "state" field.
	State ticket.State `json:"state,omitempty"`
	// Priority holds the value of the "priority" field.
	Priority ticket.Priority `json:"priority,omitempty"`
	// StateJob holds the value of the "state_job" field.
	StateJob ticket.StateJob `json:"state_job,omitempty"`
	// DataAssigned holds the value of the "data_assigned" field.
	DataAssigned *time.Time `json:"data_assigned,omitempty"`
	// DataCreation holds the value of the "data_creation" field.
	DataCreation time.Time `json:"data_creation,omitempty"`
	// DataUpdating holds the value of the "data_updating" field.
	DataUpdating time.Time `json:"data_updating,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TicketQuery when eager-loading is set.
	Edges                  TicketEdges `json:"edges"`
	company_tickets        *uuid.UUID
	service_center_tickets *uuid.UUID
	assigned_to_id         *uuid.UUID
	created_by_id          *uuid.UUID
	updated_by_id          *uuid.UUID
	selectValues           sql.SelectValues
}

// TicketEdges holds the relations/edges for other nodes in the graph.
type TicketEdges struct {
	// Company holds the value of the company edge.
	Company *Company `json:"company,omitempty"`
	// ServiceCenter holds the value of the service_center edge.
	ServiceCenter *ServiceCenter `json:"service_center,omitempty"`
	// AssignedTo holds the value of the assigned_to edge.
	AssignedTo *User `json:"assigned_to,omitempty"`
	// CreatedBy holds the value of the created_by edge.
	CreatedBy *User `json:"created_by,omitempty"`
	// UpdatedBy holds the value of the updated_by edge.
	UpdatedBy *User `json:"updated_by,omitempty"`
	// Comments holds the value of the comments edge.
	Comments []*Comment `json:"comments,omitempty"`
	// Attachments holds the value of the attachments edge.
	Attachments []*Attachment `json:"attachments,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [7]bool
}

// CompanyOrErr returns the Company value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TicketEdges) CompanyOrErr() (*Company, error) {
	if e.Company != nil {
		return e.Company, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: company.Label}
	}
	return nil, &NotLoadedError{edge: "company"}
}

// ServiceCenterOrErr returns the ServiceCenter value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TicketEdges) ServiceCenterOrErr() (*ServiceCenter, error) {
	if e.ServiceCenter != nil {
		return e.ServiceCenter, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: servicecenter.Label}
	}
	return nil, &NotLoadedError{edge: "service_center"}
}

// AssignedToOrErr returns the AssignedTo value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TicketEdges) AssignedToOrErr() (*User, error) {
	if e.AssignedTo != nil {
		return e.AssignedTo, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "assigned_to"}
}

// CreatedByOrErr returns the CreatedBy value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TicketEdges) CreatedByOrErr() (*User, error) {
	if e.CreatedBy != nil {
		return e.CreatedBy, nil
	} else if e.loadedTypes[3] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "created_by"}
}

// UpdatedByOrErr returns the UpdatedBy value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TicketEdges) UpdatedByOrErr() (*User, error) {
	if e.UpdatedBy != nil {
		return e.UpdatedBy, nil
	} else if e.loadedTypes[4] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "updated_by"}
}

// CommentsOrErr returns the Comments value or an error if the edge
// was not loaded in eager-loading.
func (e TicketEdges) CommentsOrErr() ([]*Comment, error) {
	if e.loadedTypes[5] {
		return e.Comments, nil
	}
	return nil, &NotLoadedError{edge: "comments"}
}

// AttachmentsOrErr returns the Attachments value or an error if the edge
// was not loaded in eager-loading.
func (e TicketEdges) AttachmentsOrErr() ([]*Attachment, error) {
	if e.loadedTypes[6] {
		return e.Attachments, nil
	}
	return nil, &NotLoadedError{edge: "attachments"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Ticket) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case ticket.FieldTitle, ticket.FieldQuestion, ticket.FieldState, ticket.FieldPriority, ticket.FieldStateJob:
			values[i] = new(sql.NullString)
		case ticket.FieldDataAssigned, ticket.FieldDataCreation, ticket.FieldDataUpdating:
			values[i] = new(sql.NullTime)
		case ticket.FieldID:
			values[i] = new(uuid.UUID)
		case ticket.ForeignKeys[0]: // company_tickets
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case ticket.ForeignKeys[1]: // service_center_tickets
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case ticket.ForeignKeys[2]: // assigned_to_id
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case ticket.ForeignKeys[3]: // created_by_id
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case ticket.ForeignKeys[4]: // updated_by_id
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Ticket fields.
func (t *Ticket) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case ticket.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				t.ID = *value
			}
		case ticket.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				t.Title = value.String
			}
		case ticket.FieldQuestion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field question", values[i])
			} else if value.Valid {
				t.Question = value.String
			}
		case ticket.FieldState:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field state", values[i])
			} else if value.Valid {
				t.State = ticket.State(value.String)
			}
		case ticket.FieldPriority:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field priority", values[i])
			} else if value.Valid {
				t.Priority = ticket.Priority(value.String)
			}
		case ticket.FieldStateJob:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field state_job", values[i])
			} else if value.Valid {
				t.StateJob = ticket.StateJob(value.String)
			}
		case ticket.FieldDataAssigned:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field data_assigned", values[i])
			} else if value.Valid {
				t.DataAssigned = new(time.Time)
				*t.DataAssigned = value.Time
			}
		case ticket.FieldDataCreation:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field data_creation", values[i])
			} else if value.Valid {
				t.DataCreation = value.Time
			}
		case ticket.FieldDataUpdating:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field data_updating", values[i])
			} else if value.Valid {
				t.DataUpdating = value.Time
			}
		case ticket.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field company_tickets", values[i])
			} else if value.Valid {
				t.company_tickets = new(uuid.UUID)
				*t.company_tickets = *value.S.(*uuid.UUID)
			}
		case ticket.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field service_center_tickets", values[i])
			} else if value.Valid {
				t.service_center_tickets = new(uuid.UUID)
				*t.service_center_tickets = *value.S.(*uuid.UUID)
			}
		case ticket.ForeignKeys[2]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field assigned_to_id", values[i])
			} else if value.Valid {
				t.assigned_to_id = new(uuid.UUID)
				*t.assigned_to_id = *value.S.(*uuid.UUID)
			}
		case ticket.ForeignKeys[3]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field created_by_id", values[i])
			} else if value.Valid {
				t.created_by_id = new(uuid.UUID)
				*t.created_by_id = *value.S.(*uuid.UUID)
			}
		case ticket.ForeignKeys[4]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field updated_by_id", values[i])
			} else if value.Valid {
				t.updated_by_id = new(uuid.UUID)
				*t.updated_by_id = *value.S.(*uuid.UUID)
			}
		default:
			t.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Ticket.
// This includes values selected through modifiers, order, etc.
func (t *Ticket) Value(name string) (ent.Value, error) {
	return t.selectValues.Get(name)
}

// QueryCompany queries the "company" edge of the Ticket entity.
func (t *Ticket) QueryCompany() *CompanyQuery {
	return NewTicketClient(t.config).QueryCompany(t)
}

// QueryServiceCenter queries the "service_center" edge of the Ticket entity.
func (t *Ticket) QueryServiceCenter() *ServiceCenterQuery {
	return NewTicketClient(t.config).QueryServiceCenter(t)
}

// QueryAssignedTo queries the "assigned_to" edge of the Ticket entity.
func (t *Ticket) QueryAssignedTo() *UserQuery {
	return NewTicketClient(t.config).QueryAssignedTo(t)
}

// QueryCreatedBy queries the "created_by" edge of the Ticket entity.
func (t *Ticket) QueryCreatedBy() *UserQuery {
	return NewTicketClient(t.config).QueryCreatedBy(t)
}

// QueryUpdatedBy queries the "updated_by" edge of the Ticket entity.
func (t *Ticket) QueryUpdatedBy() *UserQuery {
	return NewTicketClient(t.config).QueryUpdatedBy(t)
}

// QueryComments queries the "comments" edge of the Ticket entity.
func (t *Ticket) QueryComments() *CommentQuery {
	return NewTicketClient(t.config).QueryComments(t)
}

// QueryAttachments queries the "attachments" edge of the Ticket entity.
func (t *Ticket) QueryAttachments() *AttachmentQuery {
	return NewTicketClient(t.config).QueryAttachments(t)
}

// Update returns a builder for updating this Ticket.
// Note that you need to call Ticket.Unwrap() before calling this method if this Ticket
// was returned from a transaction, and the transaction was committed or rolled back.
func (t *Ticket) Update() *TicketUpdateOne {
	return NewTicketClient(t.config).UpdateOne(t)
}

// Unwrap unwraps the Ticket entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (t *Ticket) Unwrap() *Ticket {
	_tx, ok := t.config.driver.(*txDriver)
	if !ok {
		panic("ent: Ticket is not a transactional entity")
	}
	t.config.driver = _tx.drv
	return t
}

// String implements the fmt.Stringer.
func (t *Ticket) String() string {
	var builder strings.Builder
	builder.WriteString("Ticket(")
	builder.WriteString(fmt.Sprintf("id=%v, ", t.ID))
	builder.WriteString("title=")
	builder.WriteString(t.Title)
	builder.WriteString(", ")
	builder.WriteString("question=")
	builder.WriteString(t.Question)
	builder.WriteString(", ")
	builder.WriteString("state=")
	builder.WriteString(fmt.Sprintf("%v", t.State))
	builder.WriteString(", ")
	builder.WriteString("priority=")
	builder.WriteString(fmt.Sprintf("%v", t.Priority))
	builder.WriteString(", ")
	builder.WriteString("state_job=")
	builder.WriteString(fmt.Sprintf("%v", t.StateJob))
	builder.WriteString(", ")
	if v := t.DataAssigned; v != nil {
		builder.WriteString("data_assigned=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("data_creation=")
	builder.WriteString(t.DataCreation.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("data_updating=")
	builder.WriteString(t.DataUpdating.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Tickets is a parsable slice of Ticket.
type Tickets []*Ticket
