// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"ticket-service/ent/attachment"
	"ticket-service/ent/comment"
	"ticket-service/ent/company"
	"ticket-service/ent/servicecenter"
	"ticket-service/ent/ticket"
	"ticket-service/ent/user"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// TicketCreate is the builder for creating a Ticket entity.
type TicketCreate struct {
	config
	mutation *TicketMutation
	hooks    []Hook
}

// SetTitle sets the "title" field.
func (tc *TicketCreate) SetTitle(s string) *TicketCreate {
	tc.mutation.SetTitle(s)
	return tc
}

// SetQuestion sets the "question" field.
func (tc *TicketCreate) SetQuestion(s string) *TicketCreate {
	tc.mutation.SetQuestion(s)
	return tc
}

// SetState sets the "state" field.
func (tc *TicketCreate) SetState(t ticket.State) *TicketCreate {
	tc.mutation.SetState(t)
	return tc
}

// SetNillableState sets the "state" field if the given value is not nil.
func (tc *TicketCreate) SetNillableState(t *ticket.State) *TicketCreate {
	if t != nil {
		tc.SetState(*t)
	}
	return tc
}

// SetPriority sets the "priority" field.
func (tc *TicketCreate) SetPriority(t ticket.Priority) *TicketCreate {
	tc.mutation.SetPriority(t)
	return tc
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (tc *TicketCreate) SetNillablePriority(t *ticket.Priority) *TicketCreate {
	if t != nil {
		tc.SetPriority(*t)
	}
	return tc
}

// SetStateJob sets the "state_job" field.
func (tc *TicketCreate) SetStateJob(tj ticket.StateJob) *TicketCreate {
	tc.mutation.SetStateJob(tj)
	return tc
}

// SetNillableStateJob sets the "state_job" field if the given value is not nil.
func (tc *TicketCreate) SetNillableStateJob(tj *ticket.StateJob) *TicketCreate {
	if tj != nil {
		tc.SetStateJob(*tj)
	}
	return tc
}

// SetDataAssigned sets the "data_assigned" field.
func (tc *TicketCreate) SetDataAssigned(t time.Time) *TicketCreate {
	tc.mutation.SetDataAssigned(t)
	return tc
}

// SetNillableDataAssigned sets the "data_assigned" field if the given value is not nil.
func (tc *TicketCreate) SetNillableDataAssigned(t *time.Time) *TicketCreate {
	if t != nil {
		tc.SetDataAssigned(*t)
	}
	return tc
}

// SetDataCreation sets the "data_creation" field.
func (tc *TicketCreate) SetDataCreation(t time.Time) *TicketCreate {
	tc.mutation.SetDataCreation(t)
	return tc
}

// SetNillableDataCreation sets the "data_creation" field if the given value is not nil.
func (tc *TicketCreate) SetNillableDataCreation(t *time.Time) *TicketCreate {
	if t != nil {
		tc.SetDataCreation(*t)
	}
	return tc
}

// SetDataUpdating sets the "data_updating" field.
func (tc *TicketCreate) SetDataUpdating(t time.Time) *TicketCreate {
	tc.mutation.SetDataUpdating(t)
	return tc
}

// SetNillableDataUpdating sets the "data_updating" field if the given value is not nil.
func (tc *TicketCreate) SetNillableDataUpdating(t *time.Time) *TicketCreate {
	if t != nil {
		tc.SetDataUpdating(*t)
	}
	return tc
}

// SetID sets the "id" field.
func (tc *TicketCreate) SetID(u uuid.UUID) *TicketCreate {
	tc.mutation.SetID(u)
	return tc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (tc *TicketCreate) SetNillableID(u *uuid.UUID) *TicketCreate {
	if u != nil {
		tc.SetID(*u)
	}
	return tc
}

// SetCompanyID sets the "company" edge to the Company entity by ID.
func (tc *TicketCreate) SetCompanyID(id uuid.UUID) *TicketCreate {
	tc.mutation.SetCompanyID(id)
	return tc
}

// SetCompany sets the "company" edge to the Company entity.
func (tc *TicketCreate) SetCompany(c *Company) *TicketCreate {
	return tc.SetCompanyID(c.ID)
}

// SetServiceCenterID sets the "service_center" edge to the ServiceCenter entity by ID.
func (tc *TicketCreate) SetServiceCenterID(id uuid.UUID) *TicketCreate {
	tc.mutation.SetServiceCenterID(id)
	return tc
}

// SetServiceCenter sets the "service_center" edge to the ServiceCenter entity.
func (tc *TicketCreate) SetServiceCenter(s *ServiceCenter) *TicketCreate {
	return tc.SetServiceCenterID(s.ID)
}

// SetAssignedToID sets the "assigned_to" edge to the User entity by ID.
func (tc *TicketCreate) SetAssignedToID(id uuid.UUID) *TicketCreate {
	tc.mutation.SetAssignedToID(id)
	return tc
}

// SetNillableAssignedToID sets the "assigned_to" edge to the User entity by ID if the given value is not nil.
func (tc *TicketCreate) SetNillableAssignedToID(id *uuid.UUID) *TicketCreate {
	if id != nil {
		tc = tc.SetAssignedToID(*id)
	}
	return tc
}

// SetAssignedTo sets the "assigned_to" edge to the User entity.
func (tc *TicketCreate) SetAssignedTo(u *User) *TicketCreate {
	return tc.SetAssignedToID(u.ID)
}

// SetCreatedByID sets the "created_by" edge to the User entity by ID.
func (tc *TicketCreate) SetCreatedByID(id uuid.UUID) *TicketCreate {
	tc.mutation.SetCreatedByID(id)
	return tc
}

// SetCreatedBy sets the "created_by" edge to the User entity.
func (tc *TicketCreate) SetCreatedBy(u *User) *TicketCreate {
	return tc.SetCreatedByID(u.ID)
}

// SetUpdatedByID sets the "updated_by" edge to the User entity by ID.
func (tc *TicketCreate) SetUpdatedByID(id uuid.UUID) *TicketCreate {
	tc.mutation.SetUpdatedByID(id)
	return tc
}

// SetNillableUpdatedByID sets the "updated_by" edge to the User entity by ID if the given value is not nil.
func (tc *TicketCreate) SetNillableUpdatedByID(id *uuid.UUID) *TicketCreate {
	if id != nil {
		tc = tc.SetUpdatedByID(*id)
	}
	return tc
}

// SetUpdatedBy sets the "updated_by" edge to the User entity.
func (tc *TicketCreate) SetUpdatedBy(u *User) *TicketCreate {
	return tc.SetUpdatedByID(u.ID)
}

// AddCommentIDs adds the "comments" edge to the Comment entity by IDs.
func (tc *TicketCreate) AddCommentIDs(ids ...uuid.UUID) *TicketCreate {
	tc.mutation.AddCommentIDs(ids...)
	return tc
}

// AddComments adds the "comments" edges to the Comment entity.
func (tc *TicketCreate) AddComments(c ...*Comment) *TicketCreate {
	ids := make([]uuid.UUID, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return tc.AddCommentIDs(ids...)
}

// AddAttachmentIDs adds the "attachments" edge to the Attachment entity by IDs.
func (tc *TicketCreate) AddAttachmentIDs(ids ...uuid.UUID) *TicketCreate {
	tc.mutation.AddAttachmentIDs(ids...)
	return tc
}

// AddAttachments adds the "attachments" edges to the Attachment entity.
func (tc *TicketCreate) AddAttachments(a ...*Attachment) *TicketCreate {
	ids := make([]uuid.UUID, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return tc.AddAttachmentIDs(ids...)
}

// Mutation returns the TicketMutation object of the builder.
func (tc *TicketCreate) Mutation() *TicketMutation {
	return tc.mutation
}

// Save creates the Ticket in the database.
func (tc *TicketCreate) Save(ctx context.Context) (*Ticket, error) {
	tc.defaults()
	return withHooks(ctx, tc.sqlSave, tc.mutation, tc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (tc *TicketCreate) SaveX(ctx context.Context) *Ticket {
	v, err := tc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tc *TicketCreate) Exec(ctx context.Context) error {
	_, err := tc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tc *TicketCreate) ExecX(ctx context.Context) {
	if err := tc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (tc *TicketCreate) defaults() {
	if _, ok := tc.mutation.State(); !ok {
		v := ticket.DefaultState
		tc.mutation.SetState(v)
	}
	if _, ok := tc.mutation.Priority(); !ok {
		v := ticket.DefaultPriority
		tc.mutation.SetPriority(v)
	}
	if _, ok := tc.mutation.StateJob(); !ok {
		v := ticket.DefaultStateJob
		tc.mutation.SetStateJob(v)
	}
	if _, ok := tc.mutation.DataCreation(); !ok {
		v := ticket.DefaultDataCreation()
		tc.mutation.SetDataCreation(v)
	}
	if _, ok := tc.mutation.DataUpdating(); !ok {
		v := ticket.DefaultDataUpdating()
		tc.mutation.SetDataUpdating(v)
	}
	if _, ok := tc.mutation.ID(); !ok {
		v := ticket.DefaultID()
		tc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tc *TicketCreate) check() error {
	if _, ok := tc.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Ticket.title"`)}
	}
	if v, ok := tc.mutation.Title(); ok {
		if err := ticket.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Ticket.title": %w`, err)}
		}
	}
	if _, ok := tc.mutation.Question(); !ok {
		return &ValidationError{Name: "question", err: errors.New(`ent: missing required field "Ticket.question"`)}
	}
	if _, ok := tc.mutation.State(); !ok {
		return &ValidationError{Name: "state", err: errors.New(`ent: missing required field "Ticket.state"`)}
	}
	if v, ok := tc.mutation.State(); ok {
		if err := ticket.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf(`ent: validator failed for field "Ticket.state": %w`, err)}
		}
	}
	if _, ok := tc.mutation.Priority(); !ok {
		return &ValidationError{Name: "priority", err: errors.New(`ent: missing required field "Ticket.priority"`)}
	}
	if v, ok := tc.mutation.Priority(); ok {
		if err := ticket.PriorityValidator(v); err != nil {
			return &ValidationError{Name: "priority", err: fmt.Errorf(`ent: validator failed for field "Ticket.priority": %w`, err)}
		}
	}
	if _, ok := tc.mutation.StateJob(); !ok {
		return &ValidationError{Name: "state_job", err: errors.New(`ent: missing required field "Ticket.state_job"`)}
	}
	if v, ok := tc.mutation.StateJob(); ok {
		if err := ticket.StateJobValidator(v); err != nil {
			return &ValidationError{Name: "state_job", err: fmt.Errorf(`ent: validator failed for field "Ticket.state_job": %w`, err)}
		}
	}
	if _, ok := tc.mutation.DataCreation(); !ok {
		return &ValidationError{Name: "data_creation", err: errors.New(`ent: missing required field "Ticket.data_creation"`)}
	}
	if _, ok := tc.mutation.DataUpdating(); !ok {
		return &ValidationError{Name: "data_updating", err: errors.New(`ent: missing required field "Ticket.data_updating"`)}
	}
	if len(tc.mutation.CompanyIDs()) == 0 {
		return &ValidationError{Name: "company", err: errors.New(`ent: missing required edge "Ticket.company"`)}
	}
	if len(tc.mutation.ServiceCenterIDs()) == 0 {
		return &ValidationError{Name: "service_center", err: errors.New(`ent: missing required edge "Ticket.service_center"`)}
	}
	if len(tc.mutation.CreatedByIDs()) == 0 {
		return &ValidationError{Name: "created_by", err: errors.New(`ent: missing required edge "Ticket.created_by"`)}
	}
	return nil
}

func (tc *TicketCreate) sqlSave(ctx context.Context) (*Ticket, error) {
	if err := tc.check(); err != nil {
		return nil, err
	}
	_node, _spec := tc.createSpec()
	if err := sqlgraph.CreateNode(ctx, tc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	tc.mutation.id = &_node.ID
	tc.mutation.done = true
	return _node, nil
}

func (tc *TicketCreate) createSpec() (*Ticket, *sqlgraph.CreateSpec) {
	var (
		_node = &Ticket{config: tc.config}
		_spec = sqlgraph.NewCreateSpec(ticket.Table, sqlgraph.NewFieldSpec(ticket.FieldID, field.TypeUUID))
	)
	if id, ok := tc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := tc.mutation.Title(); ok {
		_spec.SetField(ticket.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := tc.mutation.Question(); ok {
		_spec.SetField(ticket.FieldQuestion, field.TypeString, value)
		_node.Question = value
	}
	if value, ok := tc.mutation.State(); ok {
		_spec.SetField(ticket.FieldState, field.TypeEnum, value)
		_node.State = value
	}
	if value, ok := tc.mutation.Priority(); ok {
		_spec.SetField(ticket.FieldPriority, field.TypeEnum, value)
		_node.Priority = value
	}
	if value, ok := tc.mutation.StateJob(); ok {
		_spec.SetField(ticket.FieldStateJob, field.TypeEnum, value)
		_node.StateJob = value
	}
	if value, ok := tc.mutation.DataAssigned(); ok {
		_spec.SetField(ticket.FieldDataAssigned, field.TypeTime, value)
		_node.DataAssigned = &value
	}
	if value, ok := tc.mutation.DataCreation(); ok {
		_spec.SetField(ticket.FieldDataCreation, field.TypeTime, value)
		_node.DataCreation = value
	}
	if value, ok := tc.mutation.DataUpdating(); ok {
		_spec.SetField(ticket.FieldDataUpdating, field.TypeTime, value)
		_node.DataUpdating = value
	}
	if nodes := tc.mutation.CompanyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ticket.CompanyTable,
			Columns: []string{ticket.CompanyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(company.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.company_tickets = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := tc.mutation.ServiceCenterIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ticket.ServiceCenterTable,
			Columns: []string{ticket.ServiceCenterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(servicecenter.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.service_center_tickets = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := tc.mutation.AssignedToIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ticket.AssignedToTable,
			Columns: []string{ticket.AssignedToColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.assigned_to_id = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := tc.mutation.CreatedByIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ticket.CreatedByTable,
			Columns: []string{ticket.CreatedByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.created_by_id = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := tc.mutation.UpdatedByIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ticket.UpdatedByTable,
			Columns: []string{ticket.UpdatedByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.updated_by_id = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := tc.mutation.CommentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ticket.CommentsTable,
			Columns: []string{ticket.CommentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(comment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := tc.mutation.AttachmentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ticket.AttachmentsTable,
			Columns: []string{ticket.AttachmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attachment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// TicketCreateBulk is the builder for creating many Ticket entities in bulk.
type TicketCreateBulk struct {
	config
	err      error
	builders []*TicketCreate
}

// Save creates the Ticket entities in the database.
func (tcb *TicketCreateBulk) Save(ctx context.Context) ([]*Ticket, error) {
	if tcb.err != nil {
		return nil, tcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(tcb.builders))
	nodes := make([]*Ticket, len(tcb.builders))
	mutators := make([]Mutator, len(tcb.builders))
	for i := range tcb.builders {
		func(i int, root context.Context) {
			builder := tcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TicketMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, tcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, tcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, tcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (tcb *TicketCreateBulk) SaveX(ctx context.Context) []*Ticket {
	v, err := tcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tcb *TicketCreateBulk) Exec(ctx context.Context) error {
	_, err := tcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tcb *TicketCreateBulk) ExecX(ctx context.Context) {
	if err := tcb.Exec(ctx); err != nil {
		panic(err)
	}
}
