// Code generated by ent, DO NOT EDIT.

package servicecenter

import (
	"ticket-service/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.ServiceCenter {
	return predicate.ServiceCenter(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.ServiceCenter {
	return predicate.ServiceCenter(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.ServiceCenter {
	return predicate.ServiceCenter(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.ServiceCenter {
	return predicate.ServiceCenter(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.ServiceCenter {
	return predicate.ServiceCenter(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.ServiceCenter {
	return predicate.ServiceCenter(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.ServiceCenter {
	return predicate.ServiceCenter(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.ServiceCenter {
	return predicate.ServiceCenter(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.ServiceCenter {
	return predicate.ServiceCenter(sql.FieldLTE(FieldID, id))
}

// Codice applies equality check predicate on the "codice" field. It's identical to CodiceEQ.
func Codice(v string) predicate.ServiceCenter {
	return predicate.ServiceCenter(sql.FieldEQ(FieldCodice, v))
}

// Nome applies equality check predicate on the "nome" field. It's identical to NomeEQ.
func Nome(v string) predicate.ServiceCenter {
	return predicate.ServiceCenter(sql.FieldEQ(FieldNome, v))
}

// Active applies equality check predicate on the "active" field. It's identical to ActiveEQ.
func Active(v bool) predicate.ServiceCenter {
	return predicate.ServiceCenter(sql.FieldEQ(FieldActive, v))
}

// CodiceEQ applies the EQ predicate on the "codice" field.
func CodiceEQ(v string) predicate.ServiceCenter {
	return predicate.ServiceCenter(sql.FieldEQ(FieldCodice, v))
}

// CodiceNEQ applies the NEQ predicate on the "codice" field.
func CodiceNEQ(v string) predicate.ServiceCenter {
	return predicate.ServiceCenter(sql.FieldNEQ(FieldCodice, v))
}

// CodiceIn applies the In predicate on the "codice" field.
func CodiceIn(vs ...string) predicate.ServiceCenter {
	return predicate.ServiceCenter(sql.FieldIn(FieldCodice, vs...))
}

// CodiceNotIn applies the NotIn predicate on the "codice" field.
func CodiceNotIn(vs ...string) predicate.ServiceCenter {
	return predicate.ServiceCenter(sql.FieldNotIn(FieldCodice, vs...))
}

// CodiceGT applies the GT predicate on the "codice" field.
func CodiceGT(v string) predicate.ServiceCenter {
	return predicate.ServiceCenter(sql.FieldGT(FieldCodice, v))
}

// CodiceGTE applies the GTE predicate on the "codice" field.
func CodiceGTE(v string) predicate.ServiceCenter {
	return predicate.ServiceCenter(sql.FieldGTE(FieldCodice, v))
}

// CodiceLT applies the LT predicate on the "codice" field.
func CodiceLT(v string) predicate.ServiceCenter {
	return predicate.ServiceCenter(sql.FieldLT(FieldCodice, v))
}

// CodiceLTE applies the LTE predicate on the "codice" field.
func CodiceLTE(v string) predicate.ServiceCenter {
	return predicate.ServiceCenter(sql.FieldLTE(FieldCodice, v))
}

// CodiceContains applies the Contains predicate on the "codice" field.
func CodiceContains(v string) predicate.ServiceCenter {
	return predicate.ServiceCenter(sql.FieldContains(FieldCodice, v))
}

// CodiceHasPrefix applies the HasPrefix predicate on the "codice" field.
func CodiceHasPrefix(v string) predicate.ServiceCenter {
	return predicate.ServiceCenter(sql.FieldHasPrefix(FieldCodice, v))
}

// CodiceHasSuffix applies the HasSuffix predicate on the "codice" field.
func CodiceHasSuffix(v string) predicate.ServiceCenter {
	return predicate.ServiceCenter(sql.FieldHasSuffix(FieldCodice, v))
}

// CodiceEqualFold applies the EqualFold predicate on the "codice" field.
func CodiceEqualFold(v string) predicate.ServiceCenter {
	return predicate.ServiceCenter(sql.FieldEqualFold(FieldCodice, v))
}

// CodiceContainsFold applies the ContainsFold predicate on the "codice" field.
func CodiceContainsFold(v string) predicate.ServiceCenter {
	return predicate.ServiceCenter(sql.FieldContainsFold(FieldCodice, v))
}

// NomeEQ applies the EQ predicate on the "nome" field.
func NomeEQ(v string) predicate.ServiceCenter {
	return predicate.ServiceCenter(sql.FieldEQ(FieldNome, v))
}

// NomeNEQ applies the NEQ predicate on the "nome" field.
func NomeNEQ(v string) predicate.ServiceCenter {
	return predicate.ServiceCenter(sql.FieldNEQ(FieldNome, v))
}

// NomeIn applies the In predicate on the "nome" field.
func NomeIn(vs ...string) predicate.ServiceCenter {
	return predicate.ServiceCenter(sql.FieldIn(FieldNome, vs...))
}

// NomeNotIn applies the NotIn predicate on the "nome" field.
func NomeNotIn(vs ...string) predicate.ServiceCenter {
	return predicate.ServiceCenter(sql.FieldNotIn(FieldNome, vs...))
}

// NomeGT applies the GT predicate on the "nome" field.
func NomeGT(v string) predicate.ServiceCenter {
	return predicate.ServiceCenter(sql.FieldGT(FieldNome, v))
}

// NomeGTE applies the GTE predicate on the "nome" field.
func NomeGTE(v string) predicate.ServiceCenter {
	return predicate.ServiceCenter(sql.FieldGTE(FieldNome, v))
}

// NomeLT applies the LT predicate on the "nome" field.
func NomeLT(v string) predicate.ServiceCenter {
	return predicate.ServiceCenter(sql.FieldLT(FieldNome, v))
}

// NomeLTE applies the LTE predicate on the "nome" field.
func NomeLTE(v string) predicate.ServiceCenter {
	return predicate.ServiceCenter(sql.FieldLTE(FieldNome, v))
}

// NomeContains applies the Contains predicate on the "nome" field.
func NomeContains(v string) predicate.ServiceCenter {
	return predicate.ServiceCenter(sql.FieldContains(FieldNome, v))
}

// NomeHasPrefix applies the HasPrefix predicate on the "nome" field.
func NomeHasPrefix(v string) predicate.ServiceCenter {
	return predicate.ServiceCenter(sql.FieldHasPrefix(FieldNome, v))
}

// NomeHasSuffix applies the HasSuffix predicate on the "nome" field.
func NomeHasSuffix(v string) predicate.ServiceCenter {
	return predicate.ServiceCenter(sql.FieldHasSuffix(FieldNome, v))
}

// NomeEqualFold applies the EqualFold predicate on the "nome" field.
func NomeEqualFold(v string) predicate.ServiceCenter {
	return predicate.ServiceCenter(sql.FieldEqualFold(FieldNome, v))
}

// NomeContainsFold applies the ContainsFold predicate on the "nome" field.
func NomeContainsFold(v string) predicate.ServiceCenter {
	return predicate.ServiceCenter(sql.FieldContainsFold(FieldNome, v))
}

// ActiveEQ applies the EQ predicate on the "active" field.
func ActiveEQ(v bool) predicate.ServiceCenter {
	return predicate.ServiceCenter(sql.FieldEQ(FieldActive, v))
}

// ActiveNEQ applies the NEQ predicate on the "active" field.
func ActiveNEQ(v bool) predicate.ServiceCenter {
	return predicate.ServiceCenter(sql.FieldNEQ(FieldActive, v))
}

// HasUsers applies the HasEdge predicate on the "users" edge.
func HasUsers() predicate.ServiceCenter {
	return predicate.ServiceCenter(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, UsersTable, UsersColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUsersWith applies the HasEdge predicate on the "users" edge with a given conditions (other predicates).
func HasUsersWith(preds ...predicate.User) predicate.ServiceCenter {
	return predicate.ServiceCenter(func(s *sql.Selector) {
		step := newUsersStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTickets applies the HasEdge predicate on the "tickets" edge.
func HasTickets() predicate.ServiceCenter {
	return predicate.ServiceCenter(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, TicketsTable, TicketsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTicketsWith applies the HasEdge predicate on the "tickets" edge with a given conditions (other predicates).
func HasTicketsWith(preds ...predicate.Ticket) predicate.ServiceCenter {
	return predicate.ServiceCenter(func(s *sql.Selector) {
		step := newTicketsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ServiceCenter) predicate.ServiceCenter {
	return predicate.ServiceCenter(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ServiceCenter) predicate.ServiceCenter {
	return predicate.ServiceCenter(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ServiceCenter) predicate.ServiceCenter {
	return predicate.ServiceCenter(sql.NotPredicates(p))
}
