// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Attachment is the predicate function for attachment builders.
type Attachment func(*sql.Selector)

// Comment is the predicate function for comment builders.
type Comment func(*sql.Selector)

// Company is the predicate function for company builders.
type Company func(*sql.Selector)

// ServiceCenter is the predicate function for servicecenter builders.
type ServiceCenter func(*sql.Selector)

// Ticket is the predicate function for ticket builders.
type Ticket func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
